package gov.ca.dir.acct.cars.adf.usecase030.model.view;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 06 12:00:57 PDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CarsRequestViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PacketId {
            public Object get(CarsRequestViewRowImpl obj) {
                return obj.getPacketId();
            }

            public void put(CarsRequestViewRowImpl obj, Object value) {
                obj.setPacketId((String)value);
            }
        }
        ,
        RequestId {
            public Object get(CarsRequestViewRowImpl obj) {
                return obj.getRequestId();
            }

            public void put(CarsRequestViewRowImpl obj, Object value) {
                obj.setRequestId((BigDecimal)value);
            }
        }
        ,
        Status {
            public Object get(CarsRequestViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(CarsRequestViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(CarsRequestViewRowImpl object);

        public abstract void put(CarsRequestViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PACKETID = AttributesEnum.PacketId.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int STATUS = AttributesEnum.Status.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CarsRequestViewRowImpl() {
    }

    /**
     * Gets CarsRequest entity object.
     * @return the CarsRequest
     */
    public EntityImpl getCarsRequest() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for PACKET_ID using the alias name PacketId.
     * @return the PACKET_ID
     */
    public String getPacketId() {
        return (String) getAttributeInternal(PACKETID);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKET_ID using the alias name PacketId.
     * @param value value to set the PACKET_ID
     */
    public void setPacketId(String value) {
        setAttributeInternal(PACKETID, value);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId.
     * @return the REQUEST_ID
     */
    public BigDecimal getRequestId() {
        return (BigDecimal) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId(BigDecimal value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
