package gov.ca.dir.acct.cars.adf.usecase030.model.view;

import oracle.jbo.domain.Array;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 06 12:00:57 PDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CarsRequestViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CarsRequestViewImpl() {
    }

    /**
     * Returns the bind variable value for CurrentDocument.
     * @return bind variable value for CurrentDocument
     */
    public Array getCurrentDocument() {
        return (Array)getNamedWhereClauseParam("CurrentDocument");
    }

    /**
     * Sets <code>value</code> for bind variable CurrentDocument.
     * @param value value to bind as CurrentDocument
     */
    public void setCurrentDocument(Array value) {
        setNamedWhereClauseParam("CurrentDocument", value);
    }
}
