package gov.ca.dir.acct.cars.adf.usecase030.model.view;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 14 08:56:07 PDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EventViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EventViewImpl() {
    }

    /**
     * Returns the variable value for varArRootDocument.
     * @return variable value for varArRootDocument
     */
    public String getvarArRootDocument() {
        return (String)ensureVariableManager().getVariableValue("varArRootDocument");
    }

    /**
     * Sets <code>value</code> for variable varArRootDocument.
     * @param value value to bind as varArRootDocument
     */
    public void setvarArRootDocument(String value) {
        ensureVariableManager().setVariableValue("varArRootDocument", value);
    }

    /**
     * Returns the variable value for varCurrentDocument.
     * @return variable value for varCurrentDocument
     */
    public String getvarCurrentDocument() {
        return (String)ensureVariableManager().getVariableValue("varCurrentDocument");
    }

    /**
     * Sets <code>value</code> for variable varCurrentDocument.
     * @param value value to bind as varCurrentDocument
     */
    public void setvarCurrentDocument(String value) {
        ensureVariableManager().setVariableValue("varCurrentDocument", value);
    }

    /**
     * Returns the variable value for varDataSourceCode.
     * @return variable value for varDataSourceCode
     */
    public String getvarDataSourceCode() {
        return (String)ensureVariableManager().getVariableValue("varDataSourceCode");
    }

    /**
     * Sets <code>value</code> for variable varDataSourceCode.
     * @param value value to bind as varDataSourceCode
     */
    public void setvarDataSourceCode(String value) {
        ensureVariableManager().setVariableValue("varDataSourceCode", value);
    }

    /**
     * Returns the variable value for varProgramUnitCode.
     * @return variable value for varProgramUnitCode
     */
    public String getvarProgramUnitCode() {
        return (String)ensureVariableManager().getVariableValue("varProgramUnitCode");
    }

    /**
     * Sets <code>value</code> for variable varProgramUnitCode.
     * @param value value to bind as varProgramUnitCode
     */
    public void setvarProgramUnitCode(String value) {
        ensureVariableManager().setVariableValue("varProgramUnitCode", value);
    }

    /**
     * Returns the variable value for varEventTypeCode.
     * @return variable value for varEventTypeCode
     */
    public String getvarEventTypeCode() {
        return (String)ensureVariableManager().getVariableValue("varEventTypeCode");
    }

    /**
     * Sets <code>value</code> for variable varEventTypeCode.
     * @param value value to bind as varEventTypeCode
     */
    public void setvarEventTypeCode(String value) {
        ensureVariableManager().setVariableValue("varEventTypeCode", value);
    }

    /**
     * Returns the variable value for varEventBeginDate.
     * @return variable value for varEventBeginDate
     */
    public Date getvarEventBeginDate() {
        return (Date)ensureVariableManager().getVariableValue("varEventBeginDate");
    }

    /**
     * Sets <code>value</code> for variable varEventBeginDate.
     * @param value value to bind as varEventBeginDate
     */
    public void setvarEventBeginDate(Date value) {
        ensureVariableManager().setVariableValue("varEventBeginDate", value);
    }

    /**
     * Returns the variable value for varEventEndDate.
     * @return variable value for varEventEndDate
     */
    public Date getvarEventEndDate() {
        return (Date)ensureVariableManager().getVariableValue("varEventEndDate");
    }

    /**
     * Sets <code>value</code> for variable varEventEndDate.
     * @param value value to bind as varEventEndDate
     */
    public void setvarEventEndDate(Date value) {
        ensureVariableManager().setVariableValue("varEventEndDate", value);
    }
}
