package gov.ca.dir.acct.cars.adf.usecase030.model.view;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 14 08:56:07 PDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EventViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ArRootDocument {
            public Object get(EventViewRowImpl obj) {
                return obj.getArRootDocument();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setArRootDocument((String)value);
            }
        }
        ,
        EventDate {
            public Object get(EventViewRowImpl obj) {
                return obj.getEventDate();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setEventDate((Date)value);
            }
        }
        ,
        CurrentDocument {
            public Object get(EventViewRowImpl obj) {
                return obj.getCurrentDocument();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setCurrentDocument((String)value);
            }
        }
        ,
        ReferenceDocument {
            public Object get(EventViewRowImpl obj) {
                return obj.getReferenceDocument();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setReferenceDocument((String)value);
            }
        }
        ,
        DataSourceCode {
            public Object get(EventViewRowImpl obj) {
                return obj.getDataSourceCode();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setDataSourceCode((String)value);
            }
        }
        ,
        EventTypeCode {
            public Object get(EventViewRowImpl obj) {
                return obj.getEventTypeCode();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setEventTypeCode((String)value);
            }
        }
        ,
        ProgramUnitCode {
            public Object get(EventViewRowImpl obj) {
                return obj.getProgramUnitCode();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setProgramUnitCode((String)value);
            }
        }
        ,
        EventId {
            public Object get(EventViewRowImpl obj) {
                return obj.getEventId();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setEventId((BigDecimal)value);
            }
        }
        ,
        EventTypeId {
            public Object get(EventViewRowImpl obj) {
                return obj.getEventTypeId();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setEventTypeId((BigDecimal)value);
            }
        }
        ,
        EventId1 {
            public Object get(EventViewRowImpl obj) {
                return obj.getEventId1();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setEventId1((BigDecimal)value);
            }
        }
        ,
        CreatedBy {
            public Object get(EventViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(EventViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        FsProcessStatus {
            public Object get(EventViewRowImpl obj) {
                return obj.getFsProcessStatus();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setFsProcessStatus((String)value);
            }
        }
        ,
        IsSentToCalstars {
            public Object get(EventViewRowImpl obj) {
                return obj.getIsSentToCalstars();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setIsSentToCalstars((String)value);
            }
        }
        ,
        ProgramUnitCodeView1 {
            public Object get(EventViewRowImpl obj) {
                return obj.getProgramUnitCodeView1();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DataSourceCodeView1 {
            public Object get(EventViewRowImpl obj) {
                return obj.getDataSourceCodeView1();
            }

            public void put(EventViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(EventViewRowImpl object);

        public abstract void put(EventViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ARROOTDOCUMENT = AttributesEnum.ArRootDocument.index();
    public static final int EVENTDATE = AttributesEnum.EventDate.index();
    public static final int CURRENTDOCUMENT = AttributesEnum.CurrentDocument.index();
    public static final int REFERENCEDOCUMENT = AttributesEnum.ReferenceDocument.index();
    public static final int DATASOURCECODE = AttributesEnum.DataSourceCode.index();
    public static final int EVENTTYPECODE = AttributesEnum.EventTypeCode.index();
    public static final int PROGRAMUNITCODE = AttributesEnum.ProgramUnitCode.index();
    public static final int EVENTID = AttributesEnum.EventId.index();
    public static final int EVENTTYPEID = AttributesEnum.EventTypeId.index();
    public static final int EVENTID1 = AttributesEnum.EventId1.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int FSPROCESSSTATUS = AttributesEnum.FsProcessStatus.index();
    public static final int ISSENTTOCALSTARS = AttributesEnum.IsSentToCalstars.index();
    public static final int PROGRAMUNITCODEVIEW1 = AttributesEnum.ProgramUnitCodeView1.index();
    public static final int DATASOURCECODEVIEW1 = AttributesEnum.DataSourceCodeView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EventViewRowImpl() {
    }

    /**
     * Gets Event entity object.
     * @return the Event
     */
    public EntityImpl getEvent() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets EventType entity object.
     * @return the EventType
     */
    public EntityImpl getEventType() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets EventAssociation entity object.
     * @return the EventAssociation
     */
    public EntityImpl getEventAssociation() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets Event1 entity object.
     * @return the Event1
     */
    public EntityImpl getReverseEvent() {
        return (EntityImpl)getEntity(3);
    }


    /**
     * Gets the attribute value for AR_ROOT_DOCUMENT using the alias name ArRootDocument.
     * @return the AR_ROOT_DOCUMENT
     */
    public String getArRootDocument() {
        return (String) getAttributeInternal(ARROOTDOCUMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for AR_ROOT_DOCUMENT using the alias name ArRootDocument.
     * @param value value to set the AR_ROOT_DOCUMENT
     */
    public void setArRootDocument(String value) {
        setAttributeInternal(ARROOTDOCUMENT, value);
    }

    /**
     * Gets the attribute value for EVENT_DATE using the alias name EventDate.
     * @return the EVENT_DATE
     */
    public Date getEventDate() {
        return (Date) getAttributeInternal(EVENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EVENT_DATE using the alias name EventDate.
     * @param value value to set the EVENT_DATE
     */
    public void setEventDate(Date value) {
        setAttributeInternal(EVENTDATE, value);
    }

    /**
     * Gets the attribute value for CURRENT_DOCUMENT using the alias name CurrentDocument.
     * @return the CURRENT_DOCUMENT
     */
    public String getCurrentDocument() {
        return (String) getAttributeInternal(CURRENTDOCUMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENT_DOCUMENT using the alias name CurrentDocument.
     * @param value value to set the CURRENT_DOCUMENT
     */
    public void setCurrentDocument(String value) {
        setAttributeInternal(CURRENTDOCUMENT, value);
    }

    /**
     * Gets the attribute value for REFERENCE_DOCUMENT using the alias name ReferenceDocument.
     * @return the REFERENCE_DOCUMENT
     */
    public String getReferenceDocument() {
        return (String) getAttributeInternal(REFERENCEDOCUMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_DOCUMENT using the alias name ReferenceDocument.
     * @param value value to set the REFERENCE_DOCUMENT
     */
    public void setReferenceDocument(String value) {
        setAttributeInternal(REFERENCEDOCUMENT, value);
    }

    /**
     * Gets the attribute value for DATA_SOURCE_CODE using the alias name DataSourceCode.
     * @return the DATA_SOURCE_CODE
     */
    public String getDataSourceCode() {
        return (String) getAttributeInternal(DATASOURCECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_SOURCE_CODE using the alias name DataSourceCode.
     * @param value value to set the DATA_SOURCE_CODE
     */
    public void setDataSourceCode(String value) {
        setAttributeInternal(DATASOURCECODE, value);
    }

    /**
     * Gets the attribute value for EVENT_TYPE_CODE using the alias name EventTypeCode.
     * @return the EVENT_TYPE_CODE
     */
    public String getEventTypeCode() {
        return (String) getAttributeInternal(EVENTTYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for EVENT_TYPE_CODE using the alias name EventTypeCode.
     * @param value value to set the EVENT_TYPE_CODE
     */
    public void setEventTypeCode(String value) {
        setAttributeInternal(EVENTTYPECODE, value);
    }

    /**
     * Gets the attribute value for PROGRAM_UNIT_CODE using the alias name ProgramUnitCode.
     * @return the PROGRAM_UNIT_CODE
     */
    public String getProgramUnitCode() {
        return (String) getAttributeInternal(PROGRAMUNITCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROGRAM_UNIT_CODE using the alias name ProgramUnitCode.
     * @param value value to set the PROGRAM_UNIT_CODE
     */
    public void setProgramUnitCode(String value) {
        setAttributeInternal(PROGRAMUNITCODE, value);
    }

    /**
     * Gets the attribute value for EVENT_ID using the alias name EventId.
     * @return the EVENT_ID
     */
    public BigDecimal getEventId() {
        return (BigDecimal) getAttributeInternal(EVENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for EVENT_ID using the alias name EventId.
     * @param value value to set the EVENT_ID
     */
    public void setEventId(BigDecimal value) {
        setAttributeInternal(EVENTID, value);
    }

    /**
     * Gets the attribute value for EVENT_TYPE_ID using the alias name EventTypeId.
     * @return the EVENT_TYPE_ID
     */
    public BigDecimal getEventTypeId() {
        return (BigDecimal) getAttributeInternal(EVENTTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EVENT_TYPE_ID using the alias name EventTypeId.
     * @param value value to set the EVENT_TYPE_ID
     */
    public void setEventTypeId(BigDecimal value) {
        setAttributeInternal(EVENTTYPEID, value);
    }

    /**
     * Gets the attribute value for EVENT_ID using the alias name EventId1.
     * @return the EVENT_ID
     */
    public BigDecimal getEventId1() {
        return (BigDecimal) getAttributeInternal(EVENTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for EVENT_ID using the alias name EventId1.
     * @param value value to set the EVENT_ID
     */
    public void setEventId1(BigDecimal value) {
        setAttributeInternal(EVENTID1, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute FsProcessStatus.
     * @return the FsProcessStatus
     */
    public String getFsProcessStatus() {
        return (String) getAttributeInternal(FSPROCESSSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FsProcessStatus.
     * @param value value to set the  FsProcessStatus
     */
    public void setFsProcessStatus(String value) {
        setAttributeInternal(FSPROCESSSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsSentToCalstars.
     * @return the IsSentToCalstars
     */
    public String getIsSentToCalstars() {
        return (String) getAttributeInternal(ISSENTTOCALSTARS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsSentToCalstars.
     * @param value value to set the  IsSentToCalstars
     */
    public void setIsSentToCalstars(String value) {
        setAttributeInternal(ISSENTTOCALSTARS, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProgramUnitCodeView1.
     */
    public RowSet getProgramUnitCodeView1() {
        return (RowSet)getAttributeInternal(PROGRAMUNITCODEVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DataSourceCodeView1.
     */
    public RowSet getDataSourceCodeView1() {
        return (RowSet)getAttributeInternal(DATASOURCECODEVIEW1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
