package gov.ca.dir.acct.cars.adf.usecase030.model.view;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 05 14:07:44 PST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PendingReclassItemsViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EventId {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getEventId();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setEventId((Number)value);
            }
        }
        ,
        ArRootDocument {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getArRootDocument();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setArRootDocument((String)value);
            }
        }
        ,
        FiscalYear {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getFiscalYear();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setFiscalYear((String)value);
            }
        }
        ,
        Acct1200000Amount {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getAcct1200000Amount();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setAcct1200000Amount((Number)value);
            }
        }
        ,
        ReclassExists {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getReclassExists();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setReclassExists((String)value);
            }
        }
        ,
        ProgramUnitCode {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getProgramUnitCode();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setProgramUnitCode((String)value);
            }
        }
        ,
        EventDate {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getEventDate();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setEventDate((Date)value);
            }
        }
        ,
        FsSequenceNumber {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getFsSequenceNumber();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setFsSequenceNumber((Number)value);
            }
        }
        ,
        StreetAddress {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getStreetAddress();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setStreetAddress((String)value);
            }
        }
        ,
        City {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getCity();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setCity((String)value);
            }
        }
        ,
        StateCode {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getStateCode();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setStateCode((String)value);
            }
        }
        ,
        ZipCode {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getZipCode();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setZipCode((String)value);
            }
        }
        ,
        OrganizationName {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getOrganizationName();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setOrganizationName((String)value);
            }
        }
        ,
        LegalName {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getLegalName();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setLegalName((String)value);
            }
        }
        ,
        Dba {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getDba();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setDba((String)value);
            }
        }
        ,
        CustId {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getCustId();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setCustId((String)value);
            }
        }
        ,
        AgencySourceCode {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getAgencySourceCode();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setAgencySourceCode((String)value);
            }
        }
        ,
        RevenueSourceCode {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getRevenueSourceCode();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setRevenueSourceCode((String)value);
            }
        }
        ,
        IndexCode {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getIndexCode();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setIndexCode((String)value);
            }
        }
        ,
        DataSourceCode {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getDataSourceCode();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setDataSourceCode((String)value);
            }
        }
        ,
        Fund {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getFund();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setFund((String)value);
            }
        }
        ,
        Viewable {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getViewable();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setViewable((Boolean)value);
            }
        }
        ,
        ProgramUnitCodeView1 {
            public Object get(PendingReclassItemsViewRowImpl obj) {
                return obj.getProgramUnitCodeView1();
            }

            public void put(PendingReclassItemsViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PendingReclassItemsViewRowImpl object);

        public abstract void put(PendingReclassItemsViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EVENTID = AttributesEnum.EventId.index();
    public static final int ARROOTDOCUMENT = AttributesEnum.ArRootDocument.index();
    public static final int FISCALYEAR = AttributesEnum.FiscalYear.index();
    public static final int ACCT1200000AMOUNT = AttributesEnum.Acct1200000Amount.index();
    public static final int RECLASSEXISTS = AttributesEnum.ReclassExists.index();
    public static final int PROGRAMUNITCODE = AttributesEnum.ProgramUnitCode.index();
    public static final int EVENTDATE = AttributesEnum.EventDate.index();
    public static final int FSSEQUENCENUMBER = AttributesEnum.FsSequenceNumber.index();
    public static final int STREETADDRESS = AttributesEnum.StreetAddress.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int STATECODE = AttributesEnum.StateCode.index();
    public static final int ZIPCODE = AttributesEnum.ZipCode.index();
    public static final int ORGANIZATIONNAME = AttributesEnum.OrganizationName.index();
    public static final int LEGALNAME = AttributesEnum.LegalName.index();
    public static final int DBA = AttributesEnum.Dba.index();
    public static final int CUSTID = AttributesEnum.CustId.index();
    public static final int AGENCYSOURCECODE = AttributesEnum.AgencySourceCode.index();
    public static final int REVENUESOURCECODE = AttributesEnum.RevenueSourceCode.index();
    public static final int INDEXCODE = AttributesEnum.IndexCode.index();
    public static final int DATASOURCECODE = AttributesEnum.DataSourceCode.index();
    public static final int FUND = AttributesEnum.Fund.index();
    public static final int VIEWABLE = AttributesEnum.Viewable.index();
    public static final int PROGRAMUNITCODEVIEW1 = AttributesEnum.ProgramUnitCodeView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PendingReclassItemsViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute EventId.
     * @return the EventId
     */
    public Number getEventId() {
        return (Number) getAttributeInternal(EVENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EventId.
     * @param value value to set the  EventId
     */
    public void setEventId(Number value) {
        setAttributeInternal(EVENTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ArRootDocument.
     * @return the ArRootDocument
     */
    public String getArRootDocument() {
        return (String) getAttributeInternal(ARROOTDOCUMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ArRootDocument.
     * @param value value to set the  ArRootDocument
     */
    public void setArRootDocument(String value) {
        setAttributeInternal(ARROOTDOCUMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FiscalYear.
     * @return the FiscalYear
     */
    public String getFiscalYear() {
        return (String) getAttributeInternal(FISCALYEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FiscalYear.
     * @param value value to set the  FiscalYear
     */
    public void setFiscalYear(String value) {
        setAttributeInternal(FISCALYEAR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Acct1200000Amount.
     * @return the Acct1200000Amount
     */
    public Number getAcct1200000Amount() {
        return (Number) getAttributeInternal(ACCT1200000AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Acct1200000Amount.
     * @param value value to set the  Acct1200000Amount
     */
    public void setAcct1200000Amount(Number value) {
        setAttributeInternal(ACCT1200000AMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ReclassExists.
     * @return the ReclassExists
     */
    public String getReclassExists() {
        return (String) getAttributeInternal(RECLASSEXISTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ReclassExists.
     * @param value value to set the  ReclassExists
     */
    public void setReclassExists(String value) {
        setAttributeInternal(RECLASSEXISTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProgramUnitCode.
     * @return the ProgramUnitCode
     */
    public String getProgramUnitCode() {
        return (String) getAttributeInternal(PROGRAMUNITCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProgramUnitCode.
     * @param value value to set the  ProgramUnitCode
     */
    public void setProgramUnitCode(String value) {
        setAttributeInternal(PROGRAMUNITCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EventDate.
     * @return the EventDate
     */
    public Date getEventDate() {
        return (Date) getAttributeInternal(EVENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EventDate.
     * @param value value to set the  EventDate
     */
    public void setEventDate(Date value) {
        setAttributeInternal(EVENTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FsSequenceNumber.
     * @return the FsSequenceNumber
     */
    public Number getFsSequenceNumber() {
        return (Number) getAttributeInternal(FSSEQUENCENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FsSequenceNumber.
     * @param value value to set the  FsSequenceNumber
     */
    public void setFsSequenceNumber(Number value) {
        setAttributeInternal(FSSEQUENCENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StreetAddress.
     * @return the StreetAddress
     */
    public String getStreetAddress() {
        return (String) getAttributeInternal(STREETADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StreetAddress.
     * @param value value to set the  StreetAddress
     */
    public void setStreetAddress(String value) {
        setAttributeInternal(STREETADDRESS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute City.
     * @return the City
     */
    public String getCity() {
        return (String) getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute City.
     * @param value value to set the  City
     */
    public void setCity(String value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StateCode.
     * @return the StateCode
     */
    public String getStateCode() {
        return (String) getAttributeInternal(STATECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StateCode.
     * @param value value to set the  StateCode
     */
    public void setStateCode(String value) {
        setAttributeInternal(STATECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ZipCode.
     * @return the ZipCode
     */
    public String getZipCode() {
        return (String) getAttributeInternal(ZIPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ZipCode.
     * @param value value to set the  ZipCode
     */
    public void setZipCode(String value) {
        setAttributeInternal(ZIPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrganizationName.
     * @return the OrganizationName
     */
    public String getOrganizationName() {
        return (String) getAttributeInternal(ORGANIZATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrganizationName.
     * @param value value to set the  OrganizationName
     */
    public void setOrganizationName(String value) {
        setAttributeInternal(ORGANIZATIONNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LegalName.
     * @return the LegalName
     */
    public String getLegalName() {
        return (String) getAttributeInternal(LEGALNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LegalName.
     * @param value value to set the  LegalName
     */
    public void setLegalName(String value) {
        setAttributeInternal(LEGALNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Dba.
     * @return the Dba
     */
    public String getDba() {
        return (String) getAttributeInternal(DBA);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Dba.
     * @param value value to set the  Dba
     */
    public void setDba(String value) {
        setAttributeInternal(DBA, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustId.
     * @return the CustId
     */
    public String getCustId() {
        return (String) getAttributeInternal(CUSTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustId.
     * @param value value to set the  CustId
     */
    public void setCustId(String value) {
        setAttributeInternal(CUSTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AgencySourceCode.
     * @return the AgencySourceCode
     */
    public String getAgencySourceCode() {
        return (String) getAttributeInternal(AGENCYSOURCECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AgencySourceCode.
     * @param value value to set the  AgencySourceCode
     */
    public void setAgencySourceCode(String value) {
        setAttributeInternal(AGENCYSOURCECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RevenueSourceCode.
     * @return the RevenueSourceCode
     */
    public String getRevenueSourceCode() {
        return (String) getAttributeInternal(REVENUESOURCECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RevenueSourceCode.
     * @param value value to set the  RevenueSourceCode
     */
    public void setRevenueSourceCode(String value) {
        setAttributeInternal(REVENUESOURCECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IndexCode.
     * @return the IndexCode
     */
    public String getIndexCode() {
        return (String) getAttributeInternal(INDEXCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IndexCode.
     * @param value value to set the  IndexCode
     */
    public void setIndexCode(String value) {
        setAttributeInternal(INDEXCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DataSourceCode.
     * @return the DataSourceCode
     */
    public String getDataSourceCode() {
        return (String) getAttributeInternal(DATASOURCECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DataSourceCode.
     * @param value value to set the  DataSourceCode
     */
    public void setDataSourceCode(String value) {
        setAttributeInternal(DATASOURCECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Fund.
     * @return the Fund
     */
    public String getFund() {
        return (String) getAttributeInternal(FUND);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Fund.
     * @param value value to set the  Fund
     */
    public void setFund(String value) {
        setAttributeInternal(FUND, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Viewable.
     * @return the Viewable
     */
    public Boolean getViewable() {
        return (Boolean) getAttributeInternal(VIEWABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Viewable.
     * @param value value to set the  Viewable
     */
    public void setViewable(Boolean value) {
        setAttributeInternal(VIEWABLE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProgramUnitCodeView1.
     */
    public RowSet getProgramUnitCodeView1() {
        return (RowSet)getAttributeInternal(PROGRAMUNITCODEVIEW1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
