package gov.ca.dir.acct.cars.adf.usecase030.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 06 09:10:25 PST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PendingReclassItemsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PendingReclassItemsViewImpl() {
    }

    /**
     * Returns the variable value for varFiscalYear.
     * @return variable value for varFiscalYear
     */
    public String getvarFiscalYear() {
        return (String)ensureVariableManager().getVariableValue("varFiscalYear");
    }

    /**
     * Sets <code>value</code> for variable varFiscalYear.
     * @param value value to bind as varFiscalYear
     */
    public void setvarFiscalYear(String value) {
        ensureVariableManager().setVariableValue("varFiscalYear", value);
    }

    /**
     * Returns the variable value for varAcct1200000Balance.
     * @return variable value for varAcct1200000Balance
     */
    public String getvarAcct1200000Balance() {
        return (String)ensureVariableManager().getVariableValue("varAcct1200000Balance");
    }

    /**
     * Sets <code>value</code> for variable varAcct1200000Balance.
     * @param value value to bind as varAcct1200000Balance
     */
    public void setvarAcct1200000Balance(String value) {
        ensureVariableManager().setVariableValue("varAcct1200000Balance", value);
    }

    /**
     * Returns the variable value for varProgramUnitCode.
     * @return variable value for varProgramUnitCode
     */
    public String getvarProgramUnitCode() {
        return (String)ensureVariableManager().getVariableValue("varProgramUnitCode");
    }

    /**
     * Sets <code>value</code> for variable varProgramUnitCode.
     * @param value value to bind as varProgramUnitCode
     */
    public void setvarProgramUnitCode(String value) {
        ensureVariableManager().setVariableValue("varProgramUnitCode", value);
    }

    /**
     * Returns the variable value for varBeginEventDate.
     * @return variable value for varBeginEventDate
     */
    public String getvarBeginEventDate() {
        return (String)ensureVariableManager().getVariableValue("varBeginEventDate");
    }

    /**
     * Sets <code>value</code> for variable varBeginEventDate.
     * @param value value to bind as varBeginEventDate
     */
    public void setvarBeginEventDate(String value) {
        ensureVariableManager().setVariableValue("varBeginEventDate", value);
    }

    /**
     * Returns the variable value for varEndEventDate.
     * @return variable value for varEndEventDate
     */
    public String getvarEndEventDate() {
        return (String)ensureVariableManager().getVariableValue("varEndEventDate");
    }

    /**
     * Sets <code>value</code> for variable varEndEventDate.
     * @param value value to bind as varEndEventDate
     */
    public void setvarEndEventDate(String value) {
        ensureVariableManager().setVariableValue("varEndEventDate", value);
    }

    /**
     * Returns the variable value for varLegalName.
     * @return variable value for varLegalName
     */
    public String getvarLegalName() {
        return (String)ensureVariableManager().getVariableValue("varLegalName");
    }

    /**
     * Sets <code>value</code> for variable varLegalName.
     * @param value value to bind as varLegalName
     */
    public void setvarLegalName(String value) {
        ensureVariableManager().setVariableValue("varLegalName", value);
    }

    /**
     * Returns the variable value for varArRootDocument.
     * @return variable value for varArRootDocument
     */
    public String getvarArRootDocument() {
        return (String)ensureVariableManager().getVariableValue("varArRootDocument");
    }

    /**
     * Sets <code>value</code> for variable varArRootDocument.
     * @param value value to bind as varArRootDocument
     */
    public void setvarArRootDocument(String value) {
        ensureVariableManager().setVariableValue("varArRootDocument", value);
    }
}
