package gov.ca.dir.acct.cars.adf.usecase030.model.view;

import oracle.jbo.domain.Array;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 03 16:08:05 PDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProcessedReclassEventViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProcessedReclassEventViewImpl() {
    }

    /**
     * Returns the variable value for CurrentDocumentArray.
     * @return variable value for CurrentDocumentArray
     */
    public Array getCurrentDocumentArray() {
        return (Array)ensureVariableManager().getVariableValue("CurrentDocumentArray");
    }

    /**
     * Sets <code>value</code> for variable CurrentDocumentArray.
     * @param value value to bind as CurrentDocumentArray
     */
    public void setCurrentDocumentArray(Array value) {
        ensureVariableManager().setVariableValue("CurrentDocumentArray", value);
    }
}
