package gov.ca.dir.acct.cars.adf.usecase009.model.view;


import gov.ca.dir.acct.cars.adf.usecase009.model.view.common.Infar001VO;

import java.math.BigDecimal;

import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 19 12:59:32 PDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Infar001VOImpl extends ViewObjectImpl implements Infar001VO {
  /**
   * This is the default constructor (do not remove).
   */
  public Infar001VOImpl() {
  }

  /**
   * Returns the variable value for infar001BatchIdBind.
   * @return variable value for infar001BatchIdBind
   */
  public BigDecimal getinfar001BatchIdBind() {
    return (BigDecimal)ensureVariableManager().getVariableValue("infar001BatchIdBind");
  }

  /**
   * Sets <code>value</code> for variable infar001BatchIdBind.
   * @param value value to bind as infar001BatchIdBind
   */
  public void setinfar001BatchIdBind(BigDecimal value) {
    ensureVariableManager().setVariableValue("infar001BatchIdBind", value);
  }
  
  public void set001BatchIdVC(BigDecimal batchId){
    //I don't use this function in the task flow
    //I made a link to connect Batch table with INFAR001 table instead
    //Why is this solution not working for 001 even though it works for 006?
      System.out.println("BATCH ID: "+batchId);
      ViewCriteria vc = getViewCriteria("Infar001BatchIdSearchVC");
      vc.resetCriteria();//resets any view criteria that might be set during design time.
      setinfar001BatchIdBind(batchId);
      applyViewCriteria(vc);
      executeQuery();
  }
}
