package gov.ca.dir.acct.cars.adf.usecase009.model.view;

import gov.ca.dir.acct.cars.adf.usecase009.model.view.common.Infar006VO;

import java.math.BigDecimal;

import oracle.jbo.ViewCriteria;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 19 11:55:36 PDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Infar006VOImpl extends ViewObjectImpl implements Infar006VO {
  /**
   * This is the default constructor (do not remove).
   */
  public Infar006VOImpl() {
  }

  /**
   * Returns the variable value for batchIdBind.
   * @return variable value for batchIdBind
   */
  public BigDecimal getbatchIdBind() {
    return (BigDecimal)ensureVariableManager().getVariableValue("batchIdBind");
  }

  /**
   * Sets <code>value</code> for variable batchIdBind.
   * @param value value to bind as batchIdBind
   */
  public void setbatchIdBind(BigDecimal value) {
    ensureVariableManager().setVariableValue("batchIdBind", value);
  }
  
  public void setBatchIdBindVC(BigDecimal batchId){
      ViewCriteria vc = getViewCriteria("Infar006VOCriteria");
      vc.resetCriteria();//resets any view criteria that might be set during design time.
      setbatchIdBind(batchId);
      applyViewCriteria(vc);
      executeQuery();
  }
}
