package gov.ca.dir.acct.cars.adf.usecase004.model.appmodule;

import gov.ca.dir.acct.cars.adf.usecase004.model.appmodule.common.InboundTransactionMngrAM;
import gov.ca.dir.acct.cars.adf.usecase004.model.view.RequestErrorLogViewImpl;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 26 23:57:44 PST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InboundTransactionMngrAMImpl extends ApplicationModuleImpl implements InboundTransactionMngrAM {
    /**
     * This is the default constructor (do not remove).
     */
    public InboundTransactionMngrAMImpl() {
    }

    /**
     * Container's getter for RequestErrorLogView1.
     * @return RequestErrorLogView1
     */
    public RequestErrorLogViewImpl getRequestErrorLogView1() {
        return (RequestErrorLogViewImpl)findViewObject("RequestErrorLogView1");
    }
    
    public void setCriteriaParams(String varStatus, String varIsReviewed){
        RequestErrorLogViewImpl vo = this.getRequestErrorLogView1();
        vo.setvarStatus(varStatus);
        vo.setvarIsReviewed(varIsReviewed);
        vo.executeQuery();
    }
}
