package gov.ca.dir.acct.cars.adf.usecase001.model.CarsEventDetails.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 02 10:05:03 PST 2014
// ---------------------------------------------------------------------
public interface CarsSearchEvents extends ApplicationModule {
    void doResetViewArRootDocuments1(String searchCriteriaName);
}
