package gov.ca.dir.acct.cars.adf.service.appmodule.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 01 14:26:04 PDT 2013
// ---------------------------------------------------------------------
public interface CarsBCLoggingServicesAM extends ApplicationModule {
    Number getRequestIdSequence();
}
