package gov.ca.dir.acct.cars.adf.service.appmodule.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 03 13:25:20 PDT 2013
// ---------------------------------------------------------------------
public interface CarsBCUtilityServicesAM extends ApplicationModule {
    Number getEventIDSequence();

    Number getARStatusIDSequence();

    Number getPartyIDSequence();

    Number getParticipantRoleIdSequence();

    Number getContactMethodIdSequence();

    Number getAddressIdSequence();

    Number getAcctgTransactionIdSequence();

    Number getAcctgEntryIdSequence();

    Number getNoteIdSequence();

    Number isEventReversed(String currentDocumentNumber);

    Number isChildrenExist(String currentDocumentNumber);

    Number is2YearsPrior(String ReferenceDocument);

    Number getCurrentBalance(String ReferenceDocument);

    Number isAROthersRefDocExisted(String ReferenceDocument);

    Number isReclassNeeded(String ReferenceDocument);

    Number isDecisionAfterReclassExisted(String ReferenceDocument,
                                         String eventDateStr,
                                         String eventTypeCode);
}
