package gov.ca.dir.acct.cars.webservices.internal.proxy;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://cssoady3.ad.dir.ca.gov:7777/soa-infra/services/default/CarsEventRouterSCA/CARSIntakeWebService?WSDL",
  targetNamespace="http://xmlns.oracle.com/CarsCompositeWorkspace/CarsEventRouterSCA/CARSIntakeWebService",
  name="CARSIntakeWebService")
public class CARSIntakeWebService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("gov.ca.dir.acct.cars.webservices.internal.proxy.CARSIntakeWebService");
      URL baseUrl = CARSIntakeWebService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            CARSIntakeWebService.class.getResource("http://cssoady3.ad.dir.ca.gov:7777/soa-infra/services/default/CarsEventRouterSCA/CARSIntakeWebService?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://cssoady3.ad.dir.ca.gov:7777/soa-infra/services/default/CarsEventRouterSCA/CARSIntakeWebService?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://cssoady3.ad.dir.ca.gov:7777/soa-infra/services/default/CarsEventRouterSCA/CARSIntakeWebService?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://cssoady3.ad.dir.ca.gov:7777/soa-infra/services/default/CarsEventRouterSCA/CARSIntakeWebService?WSDL",
          e);
    }
  }

  public CARSIntakeWebService()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/CarsCompositeWorkspace/CarsEventRouterSCA/CARSIntakeWebService",
                    "CARSIntakeWebService"));
  }

  public CARSIntakeWebService(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="execute_pt")
  public gov.ca.dir.acct.cars.webservices.internal.proxy.Execute_ptt getExecute_pt()
  {
    return (gov.ca.dir.acct.cars.webservices.internal.proxy.Execute_ptt) super.getPort(new QName("http://xmlns.oracle.com/CarsCompositeWorkspace/CarsEventRouterSCA/CARSIntakeWebService",
                                                                                                    "execute_pt"),
                                                                                          gov.ca.dir.acct.cars.webservices.internal.proxy.Execute_ptt.class);
  }

  @WebEndpoint(name="execute_pt")
  public gov.ca.dir.acct.cars.webservices.internal.proxy.Execute_ptt getExecute_pt(WebServiceFeature... features)
  {
    return (gov.ca.dir.acct.cars.webservices.internal.proxy.Execute_ptt) super.getPort(new QName("http://xmlns.oracle.com/CarsCompositeWorkspace/CarsEventRouterSCA/CARSIntakeWebService",
                                                                                                    "execute_pt"),
                                                                                          gov.ca.dir.acct.cars.webservices.internal.proxy.Execute_ptt.class,
                                                                                          features);
  }
}
