package gov.ca.dir.acct.cars.webservices.internal.proxy;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://cssoady3.ad.dir.ca.gov:7777/soa-infra/services/default/CarsEventRouterSCA/CARSIntakeWebService?WSDL",
  targetNamespace="http://xmlns.oracle.com/CarsCompositeWorkspace/CarsEventRouterSCA/CARSIntakeWebService",
  name="execute_ptt")
@XmlSeeAlso(
  { gov.ca.dir.acct.cars.webservices.internal.types.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface Execute_ptt
{
  @WebMethod(action="execute")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="execute")
  @Oneway
  public void execute(@WebParam(targetNamespace="http://www.dir.ca.gov/acct/cars/schema/common",
      partName="request", name="CARSPacket")
    gov.ca.dir.acct.cars.webservices.internal.types.CARSPacket request);
}
