package gov.ca.dir.acct.cars.adf.service.appmodule;

import gov.ca.dir.acct.cars.adf.common.code.ApplicationModuleImpl;

import gov.ca.dir.acct.cars.adf.common.code.ViewObjectImpl;
import gov.ca.dir.acct.cars.adf.service.appmodule.common.CarsBCLoggingServicesAM;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import oracle.jbo.JboException;
import oracle.jbo.domain.Number;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 01 14:24:32 PDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CarsBCLoggingServicesAMImpl extends ApplicationModuleImpl implements CarsBCLoggingServicesAM {
    /**
     * This is the default constructor (do not remove).
     */
    public CarsBCLoggingServicesAMImpl() {
    }


    /**
     * Get next Request ID sequence number.
     * @return Naumber
     */
    public oracle.jbo.domain.Number getRequestIdSequence(){
        return (new SequenceImpl("REQUEST_ID_SEQ",getDBTransaction())).getSequenceNumber();
    }
    
    /**
     * Get next Error Log ID sequence number.
     * @return Naumber
     */
    public oracle.jbo.domain.Number getErrorLogIdSequence(){
        return (new SequenceImpl("ERROR_LOG_ID_SEQ",getDBTransaction())).getSequenceNumber();
    }


    /**
     * Container's getter for CarsErrorLogView1.
     * @return CarsErrorLogView1
     */
    public ViewObjectImpl getCarsErrorLogView1() {
        return (ViewObjectImpl)findViewObject("CarsErrorLogView1");
    }

    /**
     * Container's getter for CarsErrorMessageView1.
     * @return CarsErrorMessageView1
     */
    public ViewObjectImpl getCarsErrorMessageView1() {
        return (ViewObjectImpl)findViewObject("CarsErrorMessageView1");
    }

    /**
     * Container's getter for CarsRequestView1.
     * @return CarsRequestView1
     */
    public ViewObjectImpl getCarsRequestView1() {
        return (ViewObjectImpl)findViewObject("CarsRequestView1");
    }
}
