package gov.ca.dir.acct.cars.adf.usecase004.model.appmodule.client;

import gov.ca.dir.acct.cars.adf.usecase004.model.appmodule.common.InboundTransactionMngrAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 27 00:09:29 PST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InboundTransactionMngrAMClient extends ApplicationModuleImpl implements InboundTransactionMngrAM {
    /**
     * This is the default constructor (do not remove).
     */
    public InboundTransactionMngrAMClient() {
    }

    public void setCriteriaParams(String varStatus, String varIsReviewed) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setCriteriaParams",new String [] {"java.lang.String","java.lang.String"},new Object[] {varStatus, varIsReviewed});
        return;
    }
}
