SELECT  
        EVENT.AR_ROOT_DOCUMENT, 
        NVL(ORGANIZATION.LEGAL_NAME, PERSON.FIRST_NAME || ' ' || PERSON.MIDDLE_NAME || ' ' || PERSON.LAST_NAME) AS "Legal Name",
        FUNC_GET_ISSUE_DATE(EVENT.AR_ROOT_DOCUMENT) "Issue Date",
        ACCOUNTING_CODE.INDEX_CODE,
        FUNC_GET_SETUP_DATE(EVENT.AR_ROOT_DOCUMENT) "Setup Date",
        trunc(EVENT.EVENT_DATE) "Adjustment Date",
        FUNC_GET_CURRENT_BALANCE(EVENT.AR_ROOT_DOCUMENT, ACCOUNTING_ENTRY.POSTING_DATE) "Current Balance",
        ACCOUNTING_ENTRY.AMOUNT "Adjustment Amount",
        FUNC_GET_ENDING_BALANCE(EVENT.AR_ROOT_DOCUMENT, ACCOUNTING_ENTRY.POSTING_DATE) "Ending Balance"

FROM 

ACCOUNTING_TRANSACTION
           
    INNER JOIN
        ACCOUNTING_ENTRY
            ON (ACCOUNTING_TRANSACTION.ACCTG_TRANSACTION_ID =
                ACCOUNTING_ENTRY.ACCTG_TRANSACTION_ID)
    INNER JOIN
        ACCTG_TRANSACT_EVENT_ASSOC
            ON (ACCOUNTING_TRANSACTION.ACCTG_TRANSACTION_ID =
                ACCTG_TRANSACT_EVENT_ASSOC.ACCTG_TRANSACTION_ID)
    INNER JOIN
        ACCOUNTING_CODE
            ON (ACCOUNTING_CODE.ACCOUNTING_CODE_ID =
                ACCOUNTING_ENTRY.ACCOUNTING_CODE_ID)
    INNER JOIN
        ACCOUNTING_ENTRY_TYPE
            ON (ACCOUNTING_ENTRY.ACCTG_ENTRY_TYPE_ID =
                ACCOUNTING_ENTRY_TYPE.ACCTG_ENTRY_TYPE_ID)
    INNER JOIN EVENT
            ON (EVENT.EVENT_ID = 
            ACCTG_TRANSACT_EVENT_ASSOC.EVENT_ID)
    INNER JOIN EVENT_TYPE
            ON (EVENT.EVENT_TYPE_ID = 
            EVENT_TYPE.EVENT_TYPE_ID)
    INNER JOIN PARTICIPANT_ROLE
            ON (EVENT.EVENT_ID = 
            PARTICIPANT_ROLE.EVENT_ID)
    LEFT JOIN ORGANIZATION
            ON (ORGANIZATION.PARTY_ID = 
            PARTICIPANT_ROLE.PARTY_ID)
    LEFT JOIN PERSON
            ON (PERSON.PARTY_ID =
            PARTICIPANT_ROLE.PARTY_ID)

WHERE PARTICIPANT_ROLE.PARTICIPANT_ROLE_TYPE_CODE = 'RES_PARTY' 
AND EVENT_TYPE.EVENT_TYPE_CODE IN ('110','115') 
AND FUNC_GET_ISSUE_DATE(EVENT.AR_ROOT_DOCUMENT) BETWEEN :p_start_date and :p_end_date
ORDER BY "Issue Date"