package gov.ca.dir.acct.cars.adf.usecase030.model.services;

import gov.ca.dir.acct.cars.adf.usecase030.model.view.EventViewImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 14 13:48:53 PDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReverseAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ReverseAMImpl() {
    }

    /**
     * Container's getter for EventView1.
     * @return EventView1
     */
    public EventViewImpl getEventView1() {
        return (EventViewImpl)findViewObject("EventView1");
    }


}
