package gov.ca.dir.acct.cars.adf.service.appmodule.common.serviceinterface;

import gov.ca.dir.acct.cars.adf.service.view.common.AccountingEntryStatusViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AccountingEntryViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AccountingReceivableStatusViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AccountingTransactionAssocViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AccountingTransactionViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AcctgTransactEventAssocViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AddressViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AdjustmentViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ContactMethodViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.CreditViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.DebitViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.EventAssociationViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.EventViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.GlAccountBalanceViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.NoteViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.OrganizationViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.OtherAccountTransViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ParticipantRoleViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.PartyAssociationViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.PartyRoleFSCustStatusViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.PartyViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.PersonViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ReceiptViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ReceivableViewSDO;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 16 15:58:13 PDT 2013
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/",
    name="CarsBCDataServicesAMService", wsdlLocation="gov/ca/dir/acct/cars/adf/service/appmodule/common/serviceinterface/CarsBCDataServicesAMService.wsdl")
@SDODatabinding(schemaLocation="gov/ca/dir/acct/cars/adf/service/appmodule/common/serviceinterface/CarsBCDataServicesAMService.xsd")
public interface CarsBCDataServicesAMService {


    public static final String NAME = "{/gov/ca/dir/acct/cars/adf/service/appmodule/common/}CarsBCDataServicesAMService";

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createAccountingReceivableStatus",
        operationName="createAccountingReceivableStatus")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAccountingReceivableStatus")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAccountingReceivableStatusResponse")
    @WebResult(name="result")
    AccountingReceivableStatusViewSDO createAccountingReceivableStatus(@WebParam(mode = WebParam.Mode.IN,
            name="accountingReceivableStatusView1")
        AccountingReceivableStatusViewSDO accountingReceivableStatusView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createAccountingTransactionAssoc",
        operationName="createAccountingTransactionAssoc")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAccountingTransactionAssoc")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAccountingTransactionAssocResponse")
    @WebResult(name="result")
    AccountingTransactionAssocViewSDO createAccountingTransactionAssoc(@WebParam(mode = WebParam.Mode.IN,
            name="accountingTransactionAssocView1")
        AccountingTransactionAssocViewSDO accountingTransactionAssocView1) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createAcctgTransactEventAssoc",
        operationName="createAcctgTransactEventAssoc")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAcctgTransactEventAssoc")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAcctgTransactEventAssocResponse")
    @WebResult(name="result")
    AcctgTransactEventAssocViewSDO createAcctgTransactEventAssoc(@WebParam(mode = WebParam.Mode.IN,
            name="acctgTransactEventAssocView1")
        AcctgTransactEventAssocViewSDO acctgTransactEventAssocView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createAddress",
        operationName="createAddress")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAddress")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAddressResponse")
    @WebResult(name="result")
    AddressViewSDO createAddress(@WebParam(mode = WebParam.Mode.IN, name="addressView1")
        AddressViewSDO addressView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createAdjustment",
        operationName="createAdjustment")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAdjustment")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAdjustmentResponse")
    @WebResult(name="result")
    AdjustmentViewSDO createAdjustment(@WebParam(mode = WebParam.Mode.IN,
            name="adjustmentView1")
        AdjustmentViewSDO adjustmentView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createContactMethod",
        operationName="createContactMethod")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createContactMethod")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createContactMethodResponse")
    @WebResult(name="result")
    ContactMethodViewSDO createContactMethod(@WebParam(mode = WebParam.Mode.IN,
            name="contactMethodView1")
        ContactMethodViewSDO contactMethodView1) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createEventAssociation",
        operationName="createEventAssociation")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createEventAssociation")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createEventAssociationResponse")
    @WebResult(name="result")
    EventAssociationViewSDO createEventAssociation(@WebParam(mode = WebParam.Mode.IN,
            name="eventAssociationView1")
        EventAssociationViewSDO eventAssociationView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createEvent",
        operationName="createEvent")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createEvent")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createEventResponse")
    @WebResult(name="result")
    EventViewSDO createEvent(@WebParam(mode = WebParam.Mode.IN, name="eventView1")
        EventViewSDO eventView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createGlAccountBalance",
        operationName="createGlAccountBalance")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createGlAccountBalance")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createGlAccountBalanceResponse")
    @WebResult(name="result")
    GlAccountBalanceViewSDO createGlAccountBalance(@WebParam(mode = WebParam.Mode.IN,
            name="glAccountBalanceView1")
        GlAccountBalanceViewSDO glAccountBalanceView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createNote",
        operationName="createNote")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createNote")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createNoteResponse")
    @WebResult(name="result")
    NoteViewSDO createNote(@WebParam(mode = WebParam.Mode.IN, name="noteView1")
        NoteViewSDO noteView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createOrganization",
        operationName="createOrganization")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createOrganization")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createOrganizationResponse")
    @WebResult(name="result")
    OrganizationViewSDO createOrganization(@WebParam(mode = WebParam.Mode.IN,
            name="organizationView1")
        OrganizationViewSDO organizationView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createOtherAccountTrans",
        operationName="createOtherAccountTrans")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createOtherAccountTrans")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createOtherAccountTransResponse")
    @WebResult(name="result")
    OtherAccountTransViewSDO createOtherAccountTrans(@WebParam(mode = WebParam.Mode.IN,
            name="otherAccountTransView1")
        OtherAccountTransViewSDO otherAccountTransView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createParticipantRole",
        operationName="createParticipantRole")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createParticipantRole")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createParticipantRoleResponse")
    @WebResult(name="result")
    ParticipantRoleViewSDO createParticipantRole(@WebParam(mode = WebParam.Mode.IN,
            name="participantRoleView1")
        ParticipantRoleViewSDO participantRoleView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createPartyAssociation",
        operationName="createPartyAssociation")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createPartyAssociation")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createPartyAssociationResponse")
    @WebResult(name="result")
    PartyAssociationViewSDO createPartyAssociation(@WebParam(mode = WebParam.Mode.IN,
            name="partyAssociationView1")
        PartyAssociationViewSDO partyAssociationView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createParty",
        operationName="createParty")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createParty")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createPartyResponse")
    @WebResult(name="result")
    PartyViewSDO createParty(@WebParam(mode = WebParam.Mode.IN, name="partyView1")
        PartyViewSDO partyView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createPerson",
        operationName="createPerson")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createPerson")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createPersonResponse")
    @WebResult(name="result")
    PersonViewSDO createPerson(@WebParam(mode = WebParam.Mode.IN, name="personView1")
        PersonViewSDO personView1) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createAccountingTransaction",
        operationName="createAccountingTransaction")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAccountingTransaction")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAccountingTransactionResponse")
    @WebResult(name="result")
    AccountingTransactionViewSDO createAccountingTransaction(@WebParam(mode = WebParam.Mode.IN,
            name="accountingTransactionView1")
        AccountingTransactionViewSDO accountingTransactionView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateAccountingReceivableStatus",
        operationName="updateAccountingReceivableStatus")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAccountingReceivableStatus")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAccountingReceivableStatusResponse")
    @WebResult(name="result")
    AccountingReceivableStatusViewSDO updateAccountingReceivableStatus(@WebParam(mode = WebParam.Mode.IN,
            name="accountingReceivableStatusView1")
        AccountingReceivableStatusViewSDO accountingReceivableStatusView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createCredit",
        operationName="createCredit")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createCredit")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createCreditResponse")
    @WebResult(name="result")
    CreditViewSDO createCredit(@WebParam(mode = WebParam.Mode.IN, name="creditView1")
        CreditViewSDO creditView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createDebit",
        operationName="createDebit")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createDebit")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createDebitResponse")
    @WebResult(name="result")
    DebitViewSDO createDebit(@WebParam(mode = WebParam.Mode.IN, name="debitView1")
        DebitViewSDO debitView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createReceivable",
        operationName="createReceivable")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createReceivable")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createReceivableResponse")
    @WebResult(name="result")
    ReceivableViewSDO createReceivable(@WebParam(mode = WebParam.Mode.IN,
            name="receivableView1")
        ReceivableViewSDO receivableView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateAddress",
        operationName="updateAddress")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAddress")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAddressResponse")
    @WebResult(name="result")
    AddressViewSDO updateAddress(@WebParam(mode = WebParam.Mode.IN, name="addressView1")
        AddressViewSDO addressView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateAdjustment",
        operationName="updateAdjustment")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAdjustment")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAdjustmentResponse")
    @WebResult(name="result")
    AdjustmentViewSDO updateAdjustment(@WebParam(mode = WebParam.Mode.IN,
            name="adjustmentView1")
        AdjustmentViewSDO adjustmentView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateContactMethod",
        operationName="updateContactMethod")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateContactMethod")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateContactMethodResponse")
    @WebResult(name="result")
    ContactMethodViewSDO updateContactMethod(@WebParam(mode = WebParam.Mode.IN,
            name="contactMethodView1")
        ContactMethodViewSDO contactMethodView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateEvent",
        operationName="updateEvent")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateEvent")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateEventResponse")
    @WebResult(name="result")
    EventViewSDO updateEvent(@WebParam(mode = WebParam.Mode.IN, name="eventView1")
        EventViewSDO eventView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateOrganization",
        operationName="updateOrganization")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateOrganization")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateOrganizationResponse")
    @WebResult(name="result")
    OrganizationViewSDO updateOrganization(@WebParam(mode = WebParam.Mode.IN,
            name="organizationView1")
        OrganizationViewSDO organizationView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateOtherAccountTrans",
        operationName="updateOtherAccountTrans")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateOtherAccountTrans")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateOtherAccountTransResponse")
    @WebResult(name="result")
    OtherAccountTransViewSDO updateOtherAccountTrans(@WebParam(mode = WebParam.Mode.IN,
            name="otherAccountTransView1")
        OtherAccountTransViewSDO otherAccountTransView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updatePerson",
        operationName="updatePerson")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updatePerson")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updatePersonResponse")
    @WebResult(name="result")
    PersonViewSDO updatePerson(@WebParam(mode = WebParam.Mode.IN, name="personView1")
        PersonViewSDO personView1) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateReceivable",
        operationName="updateReceivable")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateReceivable")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateReceivableResponse")
    @WebResult(name="result")
    ReceivableViewSDO updateReceivable(@WebParam(mode = WebParam.Mode.IN,
            name="receivableView1")
        ReceivableViewSDO receivableView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateAcctgTransactEventAssoc",
        operationName="updateAcctgTransactEventAssoc")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAcctgTransactEventAssoc")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAcctgTransactEventAssocResponse")
    @WebResult(name="result")
    AcctgTransactEventAssocViewSDO updateAcctgTransactEventAssoc(@WebParam(mode = WebParam.Mode.IN,
            name="acctgTransactEventAssocView1")
        AcctgTransactEventAssocViewSDO acctgTransactEventAssocView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateAccountingTransactionAssoc",
        operationName="updateAccountingTransactionAssoc")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAccountingTransactionAssoc")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAccountingTransactionAssocResponse")
    @WebResult(name="result")
    AccountingTransactionAssocViewSDO updateAccountingTransactionAssoc(@WebParam(mode = WebParam.Mode.IN,
            name="accountingTransactionAssocView1")
        AccountingTransactionAssocViewSDO accountingTransactionAssocView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateAccountingTransaction",
        operationName="updateAccountingTransaction")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAccountingTransaction")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateAccountingTransactionResponse")
    @WebResult(name="result")
    AccountingTransactionViewSDO updateAccountingTransaction(@WebParam(mode = WebParam.Mode.IN,
            name="accountingTransactionView1")
        AccountingTransactionViewSDO accountingTransactionView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateEventAssociation",
        operationName="updateEventAssociation")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateEventAssociation")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateEventAssociationResponse")
    @WebResult(name="result")
    EventAssociationViewSDO updateEventAssociation(@WebParam(mode = WebParam.Mode.IN,
            name="eventAssociationView1")
        EventAssociationViewSDO eventAssociationView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateParticipantRole",
        operationName="updateParticipantRole")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateParticipantRole")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateParticipantRoleResponse")
    @WebResult(name="result")
    ParticipantRoleViewSDO updateParticipantRole(@WebParam(mode = WebParam.Mode.IN,
            name="participantRoleView1")
        ParticipantRoleViewSDO participantRoleView1) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findContactMethodWithParam",
        operationName="findContactMethodWithParam")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findContactMethodWithParam")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findContactMethodWithParamResponse")
    @WebResult(name="result")
    List<ContactMethodViewSDO> findContactMethodWithParam(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varPartyId")
        String varPartyId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findParticipantRoleWithParam",
        operationName="findParticipantRoleWithParam")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findParticipantRoleWithParam")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findParticipantRoleWithParamResponse")
    @WebResult(name="result")
    List<ParticipantRoleViewSDO> findParticipantRoleWithParam(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varEventId")
        Integer varEventId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createAccountingEntry",
        operationName="createAccountingEntry")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAccountingEntry")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAccountingEntryResponse")
    @WebResult(name="result")
    AccountingEntryViewSDO createAccountingEntry(@WebParam(mode = WebParam.Mode.IN,
            name="accountingEntryView1")
        AccountingEntryViewSDO accountingEntryView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createAccountingEntryStatus",
        operationName="createAccountingEntryStatus")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAccountingEntryStatus")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createAccountingEntryStatusResponse")
    @WebResult(name="result")
    AccountingEntryStatusViewSDO createAccountingEntryStatus(@WebParam(mode = WebParam.Mode.IN,
            name="accountingEntryStatusView1")
        AccountingEntryStatusViewSDO accountingEntryStatusView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createReceipt",
        operationName="createReceipt")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createReceipt")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createReceiptResponse")
    @WebResult(name="result")
    ReceiptViewSDO createReceipt(@WebParam(mode = WebParam.Mode.IN, name="receiptView1")
        ReceiptViewSDO receiptView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateReceipt",
        operationName="updateReceipt")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateReceipt")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateReceiptResponse")
    @WebResult(name="result")
    ReceiptViewSDO updateReceipt(@WebParam(mode = WebParam.Mode.IN, name="receiptView1")
        ReceiptViewSDO receiptView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createPartyRoleFSCustStatus",
        operationName="createPartyRoleFSCustStatus")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createPartyRoleFSCustStatus")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createPartyRoleFSCustStatusResponse")
    @WebResult(name="result")
    PartyRoleFSCustStatusViewSDO createPartyRoleFSCustStatus(@WebParam(mode = WebParam.Mode.IN,
            name="partyRoleFSCustStatusView1")
        PartyRoleFSCustStatusViewSDO partyRoleFSCustStatusView1) throws ServiceException;
}
