package gov.ca.dir.acct.cars.adf.service.appmodule.common.serviceinterface;

import gov.ca.dir.acct.cars.adf.service.view.common.AccountingCodeLookupViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AccountingCodeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AccountingEntryTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AccountingEntryViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AccountingReceivableStatusViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AccountingTransactionViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AcctgEntryEventAssocRuleViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AcctgTransactEventAssocViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AddressViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AdjustmentTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.AgencySourceViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ArStatusTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.BillTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ContactMethodTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ContactMethodViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.CreditRuleLookupViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.DebitRuleLookupViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.EventLookupViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.EventTypeAssocRulesLookupSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.EventTypeAssociationRuleViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.EventTypeLookupViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.EventTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.FiscalPeriodLookupViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.FiscalPeriodViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.FundAllocationViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.FundViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.GlAccountAssocRuleLookupViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.GlAccountAssociationRuleViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.GlAccountTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.GlAccountViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.IndexCodeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.NoteTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.OtherTransactionTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ParticipantRoleTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ParticipantRoleViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.PartyAssociationTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.PcaCodeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ProgramUnitViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ReceiptTypeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.ReferenceCodeListLookupViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.RevenueSourceCodeViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.TestViewSDO;

import java.math.BigDecimal;

import java.sql.Date;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 30 12:17:41 PDT 2016
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/",
    name="CarsBCLookupServicesAMService", wsdlLocation="gov/ca/dir/acct/cars/adf/service/appmodule/common/serviceinterface/CarsBCLookupServicesAMService.wsdl")
@SDODatabinding(schemaLocation="gov/ca/dir/acct/cars/adf/service/appmodule/common/serviceinterface/CarsBCLookupServicesAMService.xsd")
public interface CarsBCLookupServicesAMService {


    public static final String NAME = "{/gov/ca/dir/acct/cars/adf/service/appmodule/common/}CarsBCLookupServicesAMService";

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAccountingCode",
        operationName="findAccountingCode")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingCode")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingCodeResponse")
    @WebResult(name="result")
    List<AccountingCodeViewSDO> findAccountingCode(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAccountingReceivableStatus",
        operationName="findAccountingReceivableStatus")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingReceivableStatus")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingReceivableStatusResponse")
    @WebResult(name="result")
    List<AccountingReceivableStatusViewSDO> findAccountingReceivableStatus(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAcctgEntryEventAssocRule",
        operationName="findAcctgEntryEventAssocRule")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAcctgEntryEventAssocRule")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAcctgEntryEventAssocRuleResponse")
    @WebResult(name="result")
    List<AcctgEntryEventAssocRuleViewSDO> findAcctgEntryEventAssocRule(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAdjustmentType",
        operationName="findAdjustmentType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAdjustmentType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAdjustmentTypeResponse")
    @WebResult(name="result")
    List<AdjustmentTypeViewSDO> findAdjustmentType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAgencySource",
        operationName="findAgencySource")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAgencySource")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAgencySourceResponse")
    @WebResult(name="result")
    List<AgencySourceViewSDO> findAgencySource(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findArStatusType",
        operationName="findArStatusType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findArStatusType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findArStatusTypeResponse")
    @WebResult(name="result")
    List<ArStatusTypeViewSDO> findArStatusType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findBillType",
        operationName="findBillType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findBillType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findBillTypeResponse")
    @WebResult(name="result")
    List<BillTypeViewSDO> findBillType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findContactMethodType",
        operationName="findContactMethodType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findContactMethodType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findContactMethodTypeResponse")
    @WebResult(name="result")
    List<ContactMethodTypeViewSDO> findContactMethodType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findEventTypeAssociationRule",
        operationName="findEventTypeAssociationRule")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findEventTypeAssociationRule")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findEventTypeAssociationRuleResponse")
    @WebResult(name="result")
    List<EventTypeAssociationRuleViewSDO> findEventTypeAssociationRule(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findEventType",
        operationName="findEventType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findEventType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findEventTypeResponse")
    @WebResult(name="result")
    List<EventTypeViewSDO> findEventType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findFiscalPeriod",
        operationName="findFiscalPeriod")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findFiscalPeriod")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findFiscalPeriodResponse")
    @WebResult(name="result")
    List<FiscalPeriodViewSDO> findFiscalPeriod(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findFundAllocation",
        operationName="findFundAllocation")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findFundAllocation")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findFundAllocationResponse")
    @WebResult(name="result")
    List<FundAllocationViewSDO> findFundAllocation(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findFund",
        operationName="findFund")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findFund")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findFundResponse")
    @WebResult(name="result")
    List<FundViewSDO> findFund(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findGlAccountAssociationRule",
        operationName="findGlAccountAssociationRule")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findGlAccountAssociationRule")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findGlAccountAssociationRuleResponse")
    @WebResult(name="result")
    List<GlAccountAssociationRuleViewSDO> findGlAccountAssociationRule(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findGlAccountType",
        operationName="findGlAccountType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findGlAccountType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findGlAccountTypeResponse")
    @WebResult(name="result")
    List<GlAccountTypeViewSDO> findGlAccountType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findGlAccount",
        operationName="findGlAccount")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findGlAccount")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findGlAccountResponse")
    @WebResult(name="result")
    List<GlAccountViewSDO> findGlAccount(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findIndexCode",
        operationName="findIndexCode")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findIndexCode")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findIndexCodeResponse")
    @WebResult(name="result")
    List<IndexCodeViewSDO> findIndexCode(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findOtherTransactionType",
        operationName="findOtherTransactionType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findOtherTransactionType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findOtherTransactionTypeResponse")
    @WebResult(name="result")
    List<OtherTransactionTypeViewSDO> findOtherTransactionType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findParticipantRoleType",
        operationName="findParticipantRoleType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findParticipantRoleType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findParticipantRoleTypeResponse")
    @WebResult(name="result")
    List<ParticipantRoleTypeViewSDO> findParticipantRoleType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findPartyAssociationType",
        operationName="findPartyAssociationType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findPartyAssociationType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findPartyAssociationTypeResponse")
    @WebResult(name="result")
    List<PartyAssociationTypeViewSDO> findPartyAssociationType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findPcaCode",
        operationName="findPcaCode")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findPcaCode")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findPcaCodeResponse")
    @WebResult(name="result")
    List<PcaCodeViewSDO> findPcaCode(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findProgramUnit",
        operationName="findProgramUnit")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findProgramUnit")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findProgramUnitResponse")
    @WebResult(name="result")
    List<ProgramUnitViewSDO> findProgramUnit(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findReceiptType",
        operationName="findReceiptType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findReceiptType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findReceiptTypeResponse")
    @WebResult(name="result")
    List<ReceiptTypeViewSDO> findReceiptType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findRevenueSourceCode",
        operationName="findRevenueSourceCode")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findRevenueSourceCode")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findRevenueSourceCodeResponse")
    @WebResult(name="result")
    List<RevenueSourceCodeViewSDO> findRevenueSourceCode(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findTestView1TestViewCriteria",
        operationName="findTestView1TestViewCriteria")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findTestView1TestViewCriteria")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findTestView1TestViewCriteriaResponse")
    @WebResult(name="result")
    List<TestViewSDO> findTestView1TestViewCriteria(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varIndexCode")
        String varIndexCode, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findEventTypeWithParams",
        operationName="findEventTypeWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findEventTypeWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findEventTypeWithParamsResponse")
    @WebResult(name="result")
    List<EventTypeLookupViewSDO> findEventTypeWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varEventTypeCode")
        String varEventTypeCode, @WebParam(mode = WebParam.Mode.IN, name="varProgramUnitCode")
        String varProgramUnitCode, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findEventTypeAssocRuleWithParams",
        operationName="findEventTypeAssocRuleWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findEventTypeAssocRuleWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findEventTypeAssocRuleWithParamsResponse")
    @WebResult(name="result")
    List<EventTypeAssocRulesLookupSDO> findEventTypeAssocRuleWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varFromEventType")
        String varFromEventType, @WebParam(mode = WebParam.Mode.IN, name="varToEventType")
        String varToEventType, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findFiscalPeriodWithParams",
        operationName="findFiscalPeriodWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findFiscalPeriodWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findFiscalPeriodWithParamsResponse")
    @WebResult(name="result")
    List<FiscalPeriodLookupViewSDO> findFiscalPeriodWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varFiscalDate")
        Date varFiscalDate, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findCreditRuleWithParams",
        operationName="findCreditRuleWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findCreditRuleWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findCreditRuleWithParamsResponse")
    @WebResult(name="result")
    List<CreditRuleLookupViewSDO> findCreditRuleWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varAcctgEntryTypeId")
        Integer varAcctgEntryTypeId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findGlAccountAssocRuleWithParams",
        operationName="findGlAccountAssocRuleWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findGlAccountAssocRuleWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findGlAccountAssocRuleWithParamsResponse")
    @WebResult(name="result")
    List<GlAccountAssocRuleLookupViewSDO> findGlAccountAssocRuleWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varAcctgEntryTypeId")
        String varAcctgEntryTypeId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findDebitRuleWithParams",
        operationName="findDebitRuleWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findDebitRuleWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findDebitRuleWithParamsResponse")
    @WebResult(name="result")
    List<DebitRuleLookupViewSDO> findDebitRuleWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varAcctgEntryTypeId")
        Integer varAcctgEntryTypeId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAcctgTransactEventAssocWithParams",
        operationName="findAcctgTransactEventAssocWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAcctgTransactEventAssocWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAcctgTransactEventAssocWithParamsResponse")
    @WebResult(name="result")
    List<AcctgTransactEventAssocViewSDO> findAcctgTransactEventAssocWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varEventId")
        Integer varEventId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findNoteTypeWithParams",
        operationName="findNoteTypeWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findNoteTypeWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findNoteTypeWithParamsResponse")
    @WebResult(name="result")
    List<NoteTypeViewSDO> findNoteTypeWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varNoteTypeCode")
        String varNoteTypeCode, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findContactMethodWithParam",
        operationName="findContactMethodWithParam")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findContactMethodWithParam")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findContactMethodWithParamResponse")
    @WebResult(name="result")
    List<ContactMethodViewSDO> findContactMethodWithParam(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varPartyId")
        String varPartyId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAccountingTransactionWithParams",
        operationName="findAccountingTransactionWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingTransactionWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingTransactionWithParamsResponse")
    @WebResult(name="result")
    List<AccountingTransactionViewSDO> findAccountingTransactionWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varTransactionId")
        String varTransactionId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findParticipantRoleWithParams",
        operationName="findParticipantRoleWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findParticipantRoleWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findParticipantRoleWithParamsResponse")
    @WebResult(name="result")
    List<ParticipantRoleViewSDO> findParticipantRoleWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varEventId")
        Integer varEventId, @WebParam(mode = WebParam.Mode.IN, name="varPartyRoleTypeCode")
        String varPartyRoleTypeCode, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAddressWithParams",
        operationName="findAddressWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAddressWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAddressWithParamsResponse")
    @WebResult(name="result")
    List<AddressViewSDO> findAddressWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varPartyId")
        String varPartyId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findReferenceCodeListWithParams",
        operationName="findReferenceCodeListWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findReferenceCodeListWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findReferenceCodeListWithParamsResponse")
    @WebResult(name="result")
    List<ReferenceCodeListLookupViewSDO> findReferenceCodeListWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varReferenceValue")
        String varReferenceValue, @WebParam(mode = WebParam.Mode.IN, name="varDomainName")
        String varDomainName, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findEventWithParams",
        operationName="findEventWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findEventWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findEventWithParamsResponse")
    @WebResult(name="result")
    List<EventLookupViewSDO> findEventWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varEventId")
        String varEventId, @WebParam(mode = WebParam.Mode.IN, name="varCurrentDocument")
        String varCurrentDocument, @WebParam(mode = WebParam.Mode.IN, name="varReferenceDocument")
        String varReferenceDocument, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAccountingEntryType",
        operationName="findAccountingEntryType")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingEntryType")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingEntryTypeResponse")
    @WebResult(name="result")
    List<AccountingEntryTypeViewSDO> findAccountingEntryType(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAccountingEntryTypeWithParams",
        operationName="findAccountingEntryTypeWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingEntryTypeWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingEntryTypeWithParamsResponse")
    @WebResult(name="result")
    List<AccountingEntryTypeViewSDO> findAccountingEntryTypeWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varAcctgEntryTypeId")
        String varAcctgEntryTypeId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAccountingEntryTypeReversal",
        operationName="findAccountingEntryTypeReversal")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingEntryTypeReversal")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingEntryTypeReversalResponse")
    @WebResult(name="result")
    List<AccountingEntryTypeViewSDO> findAccountingEntryTypeReversal(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varAcctgEntryTypeCode")
        String varAcctgEntryTypeCode, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAccountingEntryWithParams",
        operationName="findAccountingEntryWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingEntryWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingEntryWithParamsResponse")
    @WebResult(name="result")
    List<AccountingEntryViewSDO> findAccountingEntryWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varAcctgTransactionId")
        String varAcctgTransactionId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findAccountingCodeWithParams",
        operationName="findAccountingCodeWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingCodeWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findAccountingCodeWithParamsResponse")
    @WebResult(name="result")
    List<AccountingCodeLookupViewSDO> findAccountingCodeWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varAgencySourceCode")
        String varAgencySourceCode, @WebParam(mode = WebParam.Mode.IN, name="varRevenueSourceCode")
        String varRevenueSourceCode, @WebParam(mode = WebParam.Mode.IN, name="varIndexCode")
        String varIndexCode, @WebParam(mode = WebParam.Mode.IN, name="varEventTypeCode")
        String varEventTypeCode, @WebParam(mode = WebParam.Mode.IN, name="varEventTypeId")
        String varEventTypeId, @WebParam(mode = WebParam.Mode.IN, name="varProgramUnitCode")
        String varProgramUnitCode, @WebParam(mode = WebParam.Mode.IN, name="varTransactionCode")
        String varTransactionCode, @WebParam(mode = WebParam.Mode.IN, name="varFund")
        String varFund, @WebParam(mode = WebParam.Mode.IN, name="varFiscalPeriodId")
        String varFiscalPeriodId, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    /**
     * Exported method findFiscalPeriodIdWithParams from CarsBCLookupServicesAM.
     */
    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findFiscalPeriodIdWithParams",
        operationName="findFiscalPeriodIdWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findFiscalPeriodIdWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findFiscalPeriodIdWithParamsResponse")
    @WebResult(name="result")
    String findFiscalPeriodIdWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="rootDocument")
        String rootDocument) throws ServiceException;

    /**
     * Exported method recheckReferenceDocument from CarsBCLookupServicesAM.
     */
    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/recheckReferenceDocument",
        operationName="recheckReferenceDocument")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="recheckReferenceDocument")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="recheckReferenceDocumentResponse")
    @WebResult(name="result")
    BigDecimal recheckReferenceDocument(@WebParam(mode = WebParam.Mode.IN,
            name="referenceDocument")
        String referenceDocument, @WebParam(mode = WebParam.Mode.IN, name="processNum")
        int processNum, @WebParam(mode = WebParam.Mode.IN, name="waitTime")
        long waitTime) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findReferenceCodeListLookupView",
        operationName="findReferenceCodeListLookupView")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findReferenceCodeListLookupView")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findReferenceCodeListLookupViewResponse")
    @WebResult(name="result")
    List<ReferenceCodeListLookupViewSDO> findReferenceCodeListLookupView(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;


    /**
     * Exported method validateAddress from CarsBCLookupServicesAM.
     */
    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/validateAddress",
        operationName="validateAddress")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="validateAddress")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="validateAddressResponse")
    @WebResult(name="result")
    String validateAddress(@WebParam(mode = WebParam.Mode.IN, name="state")
        String state, @WebParam(mode = WebParam.Mode.IN, name="zipCode")
        String zipCode, @WebParam(mode = WebParam.Mode.IN, name="province")
        String province, @WebParam(mode = WebParam.Mode.IN, name="postalCode")
        String postalCode, @WebParam(mode = WebParam.Mode.IN, name="countryAbbreviation")
        String countryAbbreviation) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findSOARecipient",
        operationName="findSOARecipient")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findSOARecipient")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findSOARecipientResponse")
    @WebResult(name="result")
    List<ReferenceCodeListLookupViewSDO> findSOARecipient(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;
}
