package gov.ca.dir.acct.cars.adf.service.appmodule.common.serviceinterface;

import gov.ca.dir.acct.cars.adf.service.view.common.CarsErrorLogViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.CarsErrorMessageViewSDO;
import gov.ca.dir.acct.cars.adf.service.view.common.CarsRequestViewSDO;

import java.math.BigDecimal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 04 09:56:22 PDT 2013
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/",
    name="CarsBCLoggingServicesAMService", wsdlLocation="gov/ca/dir/acct/cars/adf/service/appmodule/common/serviceinterface/CarsBCLoggingServicesAMService.wsdl")
@SDODatabinding(schemaLocation="gov/ca/dir/acct/cars/adf/service/appmodule/common/serviceinterface/CarsBCLoggingServicesAMService.xsd")
public interface CarsBCLoggingServicesAMService {


    public static final String NAME = "{/gov/ca/dir/acct/cars/adf/service/appmodule/common/}CarsBCLoggingServicesAMService";

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createCarsErrorLog",
        operationName="createCarsErrorLog")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createCarsErrorLog")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createCarsErrorLogResponse")
    @WebResult(name="result")
    CarsErrorLogViewSDO createCarsErrorLog(@WebParam(mode = WebParam.Mode.IN,
            name="carsErrorLogView1")
        CarsErrorLogViewSDO carsErrorLogView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findCarsErrorMessageWithParams",
        operationName="findCarsErrorMessageWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findCarsErrorMessageWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findCarsErrorMessageWithParamsResponse")
    @WebResult(name="result")
    List<CarsErrorMessageViewSDO> findCarsErrorMessageWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varErrorMessageId")
        Integer varErrorMessageId, @WebParam(mode = WebParam.Mode.IN, name="varFaultCode")
        String varFaultCode, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;


    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/createCarsRequest",
        operationName="createCarsRequest")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createCarsRequest")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="createCarsRequestResponse")
    @WebResult(name="result")
    CarsRequestViewSDO createCarsRequest(@WebParam(mode = WebParam.Mode.IN,
            name="carsRequestView1")
        CarsRequestViewSDO carsRequestView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/updateCarsRequest",
        operationName="updateCarsRequest")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateCarsRequest")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="updateCarsRequestResponse")
    @WebResult(name="result")
    CarsRequestViewSDO updateCarsRequest(@WebParam(mode = WebParam.Mode.IN,
            name="carsRequestView1")
        CarsRequestViewSDO carsRequestView1) throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findCarsRequestWithParams",
        operationName="findCarsRequestWithParams")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findCarsRequestWithParams")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findCarsRequestWithParamsResponse")
    @WebResult(name="result")
    List<CarsRequestViewSDO> findCarsRequestWithParams(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varEcid")
        String varEcid, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;


    /**
     * Exported method getErrorLogIdSequence from CarsBCLoggingServicesAM.
     */
    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/getErrorLogIdSequence",
        operationName="getErrorLogIdSequence")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="getErrorLogIdSequence")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="getErrorLogIdSequenceResponse")
    @WebResult(name="result")
    BigDecimal getErrorLogIdSequence() throws ServiceException;

    /**
     * Exported method getRequestIdSequence from CarsBCLoggingServicesAM.
     */
    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/getRequestIdSequence",
        operationName="getRequestIdSequence")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="getRequestIdSequence")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="getRequestIdSequenceResponse")
    @WebResult(name="result")
    BigDecimal getRequestIdSequence() throws ServiceException;

    @WebMethod(action="/gov/ca/dir/acct/cars/adf/service/appmodule/common/findCarsRequestWithInstanceIdParam",
        operationName="findCarsRequestWithInstanceIdParam")
    @RequestWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findCarsRequestWithInstanceIdParam")
    @ResponseWrapper(targetNamespace="/gov/ca/dir/acct/cars/adf/service/appmodule/common/types/",
        localName="findCarsRequestWithInstanceIdParamResponse")
    @WebResult(name="result")
    List<CarsRequestViewSDO> findCarsRequestWithInstanceIdParam(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="varEcid")
        String varEcid, @WebParam(mode = WebParam.Mode.IN, name="varPayloadName")
        String varPayloadName, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;
}
