package gov.ca.dir.acct.cars.adf.usecase004.model.view;


import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 26 23:41:21 PST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestErrorLogViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RequestErrorLogViewImpl() {
    }

    /**
     * Returns the variable value for varStatus.
     * @return variable value for varStatus
     */
    public String getvarStatus() {
        return (String)ensureVariableManager().getVariableValue("varStatus");
    }

    /**
     * Sets <code>value</code> for variable varStatus.
     * @param value value to bind as varStatus
     */
    public void setvarStatus(String value) {
        ensureVariableManager().setVariableValue("varStatus", value);
    }

    /**
     * Returns the variable value for varIsReviewed.
     * @return variable value for varIsReviewed
     */
    public String getvarIsReviewed() {
        return (String)ensureVariableManager().getVariableValue("varIsReviewed");
    }

    /**
     * Sets <code>value</code> for variable varIsReviewed.
     * @param value value to bind as varIsReviewed
     */
    public void setvarIsReviewed(String value) {
        ensureVariableManager().setVariableValue("varIsReviewed", value);
    }
}
