package gov.ca.dir.acct.cars.adf.usecase004.model.view;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 26 23:41:20 PST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestErrorLogViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ComponentInstanceId {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getComponentInstanceId();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setComponentInstanceId((BigDecimal)value);
            }
        }
        ,
        ComponentName {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getComponentName();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setComponentName((String)value);
            }
        }
        ,
        CompositeInstanceId {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getCompositeInstanceId();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setCompositeInstanceId((String)value);
            }
        }
        ,
        ConversationId {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getConversationId();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setConversationId((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreatedDate {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getCreatedDate();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setCreatedDate((Date)value);
            }
        }
        ,
        DataSourceCode {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getDataSourceCode();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setDataSourceCode((String)value);
            }
        }
        ,
        Ecid {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getEcid();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setEcid((String)value);
            }
        }
        ,
        ErrorCode {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getErrorCode();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setErrorCode((String)value);
            }
        }
        ,
        ErrorDetail {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getErrorDetail();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setErrorDetail((String)value);
            }
        }
        ,
        ErrorLevel {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getErrorLevel();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setErrorLevel((String)value);
            }
        }
        ,
        ErrorLogId {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getErrorLogId();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setErrorLogId((BigDecimal)value);
            }
        }
        ,
        ErrorMessage {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getErrorMessage();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setErrorMessage((String)value);
            }
        }
        ,
        FaultCode {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getFaultCode();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setFaultCode((String)value);
            }
        }
        ,
        FaultLocation {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getFaultLocation();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setFaultLocation((String)value);
            }
        }
        ,
        ModifiedBy {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getModifiedBy();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setModifiedBy((String)value);
            }
        }
        ,
        ModifiedDate {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setModifiedDate((Date)value);
            }
        }
        ,
        RequestId {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getRequestId();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setRequestId((BigDecimal)value);
            }
        }
        ,
        Severity {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getSeverity();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setSeverity((String)value);
            }
        }
        ,
        EnvironmentName {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getEnvironmentName();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setEnvironmentName((String)value);
            }
        }
        ,
        PacketId {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getPacketId();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setPacketId((String)value);
            }
        }
        ,
        PacketTransport {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getPacketTransport();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setPacketTransport((String)value);
            }
        }
        ,
        PayloadName {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getPayloadName();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setPayloadName((String)value);
            }
        }
        ,
        ProgramUnitCode {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getProgramUnitCode();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setProgramUnitCode((String)value);
            }
        }
        ,
        SchemaName {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getSchemaName();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setSchemaName((String)value);
            }
        }
        ,
        SchemaVersionNumber {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getSchemaVersionNumber();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setSchemaVersionNumber((String)value);
            }
        }
        ,
        Status {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        SubmitDate {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getSubmitDate();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setSubmitDate((Date)value);
            }
        }
        ,
        SubmittedBy {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getSubmittedBy();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setSubmittedBy((String)value);
            }
        }
        ,
        RequestId1 {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getRequestId1();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setRequestId1((BigDecimal)value);
            }
        }
        ,
        IsReviewed {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getIsReviewed();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setIsReviewed((String)value);
            }
        }
        ,
        TransactionStatusLOV1 {
            public Object get(RequestErrorLogViewRowImpl obj) {
                return obj.getTransactionStatusLOV1();
            }

            public void put(RequestErrorLogViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(RequestErrorLogViewRowImpl object);

        public abstract void put(RequestErrorLogViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int COMPONENTINSTANCEID = AttributesEnum.ComponentInstanceId.index();
    public static final int COMPONENTNAME = AttributesEnum.ComponentName.index();
    public static final int COMPOSITEINSTANCEID = AttributesEnum.CompositeInstanceId.index();
    public static final int CONVERSATIONID = AttributesEnum.ConversationId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int DATASOURCECODE = AttributesEnum.DataSourceCode.index();
    public static final int ECID = AttributesEnum.Ecid.index();
    public static final int ERRORCODE = AttributesEnum.ErrorCode.index();
    public static final int ERRORDETAIL = AttributesEnum.ErrorDetail.index();
    public static final int ERRORLEVEL = AttributesEnum.ErrorLevel.index();
    public static final int ERRORLOGID = AttributesEnum.ErrorLogId.index();
    public static final int ERRORMESSAGE = AttributesEnum.ErrorMessage.index();
    public static final int FAULTCODE = AttributesEnum.FaultCode.index();
    public static final int FAULTLOCATION = AttributesEnum.FaultLocation.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int REQUESTID = AttributesEnum.RequestId.index();
    public static final int SEVERITY = AttributesEnum.Severity.index();
    public static final int ENVIRONMENTNAME = AttributesEnum.EnvironmentName.index();
    public static final int PACKETID = AttributesEnum.PacketId.index();
    public static final int PACKETTRANSPORT = AttributesEnum.PacketTransport.index();
    public static final int PAYLOADNAME = AttributesEnum.PayloadName.index();
    public static final int PROGRAMUNITCODE = AttributesEnum.ProgramUnitCode.index();
    public static final int SCHEMANAME = AttributesEnum.SchemaName.index();
    public static final int SCHEMAVERSIONNUMBER = AttributesEnum.SchemaVersionNumber.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int SUBMITDATE = AttributesEnum.SubmitDate.index();
    public static final int SUBMITTEDBY = AttributesEnum.SubmittedBy.index();
    public static final int REQUESTID1 = AttributesEnum.RequestId1.index();
    public static final int ISREVIEWED = AttributesEnum.IsReviewed.index();
    public static final int TRANSACTIONSTATUSLOV1 = AttributesEnum.TransactionStatusLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RequestErrorLogViewRowImpl() {
    }

    /**
     * Gets CarsErrorLog entity object.
     * @return the CarsErrorLog
     */
    public EntityImpl getCarsErrorLog() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets CarsRequest entity object.
     * @return the CarsRequest
     */
    public EntityImpl getCarsRequest() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets the attribute value for COMPONENT_INSTANCE_ID using the alias name ComponentInstanceId.
     * @return the COMPONENT_INSTANCE_ID
     */
    public BigDecimal getComponentInstanceId() {
        return (BigDecimal) getAttributeInternal(COMPONENTINSTANCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPONENT_INSTANCE_ID using the alias name ComponentInstanceId.
     * @param value value to set the COMPONENT_INSTANCE_ID
     */
    public void setComponentInstanceId(BigDecimal value) {
        setAttributeInternal(COMPONENTINSTANCEID, value);
    }

    /**
     * Gets the attribute value for COMPONENT_NAME using the alias name ComponentName.
     * @return the COMPONENT_NAME
     */
    public String getComponentName() {
        return (String) getAttributeInternal(COMPONENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPONENT_NAME using the alias name ComponentName.
     * @param value value to set the COMPONENT_NAME
     */
    public void setComponentName(String value) {
        setAttributeInternal(COMPONENTNAME, value);
    }

    /**
     * Gets the attribute value for COMPOSITE_INSTANCE_ID using the alias name CompositeInstanceId.
     * @return the COMPOSITE_INSTANCE_ID
     */
    public String getCompositeInstanceId() {
        return (String) getAttributeInternal(COMPOSITEINSTANCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPOSITE_INSTANCE_ID using the alias name CompositeInstanceId.
     * @param value value to set the COMPOSITE_INSTANCE_ID
     */
    public void setCompositeInstanceId(String value) {
        setAttributeInternal(COMPOSITEINSTANCEID, value);
    }

    /**
     * Gets the attribute value for CONVERSATION_ID using the alias name ConversationId.
     * @return the CONVERSATION_ID
     */
    public String getConversationId() {
        return (String) getAttributeInternal(CONVERSATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONVERSATION_ID using the alias name ConversationId.
     * @param value value to set the CONVERSATION_ID
     */
    public void setConversationId(String value) {
        setAttributeInternal(CONVERSATIONID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for DATA_SOURCE_CODE using the alias name DataSourceCode.
     * @return the DATA_SOURCE_CODE
     */
    public String getDataSourceCode() {
        return (String) getAttributeInternal(DATASOURCECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_SOURCE_CODE using the alias name DataSourceCode.
     * @param value value to set the DATA_SOURCE_CODE
     */
    public void setDataSourceCode(String value) {
        setAttributeInternal(DATASOURCECODE, value);
    }

    /**
     * Gets the attribute value for ECID using the alias name Ecid.
     * @return the ECID
     */
    public String getEcid() {
        return (String) getAttributeInternal(ECID);
    }

    /**
     * Sets <code>value</code> as attribute value for ECID using the alias name Ecid.
     * @param value value to set the ECID
     */
    public void setEcid(String value) {
        setAttributeInternal(ECID, value);
    }

    /**
     * Gets the attribute value for ERROR_CODE using the alias name ErrorCode.
     * @return the ERROR_CODE
     */
    public String getErrorCode() {
        return (String) getAttributeInternal(ERRORCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_CODE using the alias name ErrorCode.
     * @param value value to set the ERROR_CODE
     */
    public void setErrorCode(String value) {
        setAttributeInternal(ERRORCODE, value);
    }

    /**
     * Gets the attribute value for ERROR_DETAIL using the alias name ErrorDetail.
     * @return the ERROR_DETAIL
     */
    public String getErrorDetail() {
        return (String) getAttributeInternal(ERRORDETAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_DETAIL using the alias name ErrorDetail.
     * @param value value to set the ERROR_DETAIL
     */
    public void setErrorDetail(String value) {
        setAttributeInternal(ERRORDETAIL, value);
    }

    /**
     * Gets the attribute value for ERROR_LEVEL using the alias name ErrorLevel.
     * @return the ERROR_LEVEL
     */
    public String getErrorLevel() {
        return (String) getAttributeInternal(ERRORLEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_LEVEL using the alias name ErrorLevel.
     * @param value value to set the ERROR_LEVEL
     */
    public void setErrorLevel(String value) {
        setAttributeInternal(ERRORLEVEL, value);
    }

    /**
     * Gets the attribute value for ERROR_LOG_ID using the alias name ErrorLogId.
     * @return the ERROR_LOG_ID
     */
    public BigDecimal getErrorLogId() {
        return (BigDecimal) getAttributeInternal(ERRORLOGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_LOG_ID using the alias name ErrorLogId.
     * @param value value to set the ERROR_LOG_ID
     */
    public void setErrorLogId(BigDecimal value) {
        setAttributeInternal(ERRORLOGID, value);
    }

    /**
     * Gets the attribute value for ERROR_MESSAGE using the alias name ErrorMessage.
     * @return the ERROR_MESSAGE
     */
    public String getErrorMessage() {
        return (String) getAttributeInternal(ERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MESSAGE using the alias name ErrorMessage.
     * @param value value to set the ERROR_MESSAGE
     */
    public void setErrorMessage(String value) {
        setAttributeInternal(ERRORMESSAGE, value);
    }

    /**
     * Gets the attribute value for FAULT_CODE using the alias name FaultCode.
     * @return the FAULT_CODE
     */
    public String getFaultCode() {
        return (String) getAttributeInternal(FAULTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for FAULT_CODE using the alias name FaultCode.
     * @param value value to set the FAULT_CODE
     */
    public void setFaultCode(String value) {
        setAttributeInternal(FAULTCODE, value);
    }

    /**
     * Gets the attribute value for FAULT_LOCATION using the alias name FaultLocation.
     * @return the FAULT_LOCATION
     */
    public String getFaultLocation() {
        return (String) getAttributeInternal(FAULTLOCATION);
    }

    /**
     * Sets <code>value</code> as attribute value for FAULT_LOCATION using the alias name FaultLocation.
     * @param value value to set the FAULT_LOCATION
     */
    public void setFaultLocation(String value) {
        setAttributeInternal(FAULTLOCATION, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId.
     * @return the REQUEST_ID
     */
    public BigDecimal getRequestId() {
        return (BigDecimal) getAttributeInternal(REQUESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId(BigDecimal value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**
     * Gets the attribute value for SEVERITY using the alias name Severity.
     * @return the SEVERITY
     */
    public String getSeverity() {
        return (String) getAttributeInternal(SEVERITY);
    }

    /**
     * Sets <code>value</code> as attribute value for SEVERITY using the alias name Severity.
     * @param value value to set the SEVERITY
     */
    public void setSeverity(String value) {
        setAttributeInternal(SEVERITY, value);
    }

    /**
     * Gets the attribute value for ENVIRONMENT_NAME using the alias name EnvironmentName.
     * @return the ENVIRONMENT_NAME
     */
    public String getEnvironmentName() {
        return (String) getAttributeInternal(ENVIRONMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ENVIRONMENT_NAME using the alias name EnvironmentName.
     * @param value value to set the ENVIRONMENT_NAME
     */
    public void setEnvironmentName(String value) {
        setAttributeInternal(ENVIRONMENTNAME, value);
    }

    /**
     * Gets the attribute value for PACKET_ID using the alias name PacketId.
     * @return the PACKET_ID
     */
    public String getPacketId() {
        return (String) getAttributeInternal(PACKETID);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKET_ID using the alias name PacketId.
     * @param value value to set the PACKET_ID
     */
    public void setPacketId(String value) {
        setAttributeInternal(PACKETID, value);
    }

    /**
     * Gets the attribute value for PACKET_TRANSPORT using the alias name PacketTransport.
     * @return the PACKET_TRANSPORT
     */
    public String getPacketTransport() {
        return (String) getAttributeInternal(PACKETTRANSPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKET_TRANSPORT using the alias name PacketTransport.
     * @param value value to set the PACKET_TRANSPORT
     */
    public void setPacketTransport(String value) {
        setAttributeInternal(PACKETTRANSPORT, value);
    }

    /**
     * Gets the attribute value for PAYLOAD_NAME using the alias name PayloadName.
     * @return the PAYLOAD_NAME
     */
    public String getPayloadName() {
        return (String) getAttributeInternal(PAYLOADNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYLOAD_NAME using the alias name PayloadName.
     * @param value value to set the PAYLOAD_NAME
     */
    public void setPayloadName(String value) {
        setAttributeInternal(PAYLOADNAME, value);
    }

    /**
     * Gets the attribute value for PROGRAM_UNIT_CODE using the alias name ProgramUnitCode.
     * @return the PROGRAM_UNIT_CODE
     */
    public String getProgramUnitCode() {
        return (String) getAttributeInternal(PROGRAMUNITCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROGRAM_UNIT_CODE using the alias name ProgramUnitCode.
     * @param value value to set the PROGRAM_UNIT_CODE
     */
    public void setProgramUnitCode(String value) {
        setAttributeInternal(PROGRAMUNITCODE, value);
    }

    /**
     * Gets the attribute value for SCHEMA_NAME using the alias name SchemaName.
     * @return the SCHEMA_NAME
     */
    public String getSchemaName() {
        return (String) getAttributeInternal(SCHEMANAME);
    }

    /**
     * Sets <code>value</code> as attribute value for SCHEMA_NAME using the alias name SchemaName.
     * @param value value to set the SCHEMA_NAME
     */
    public void setSchemaName(String value) {
        setAttributeInternal(SCHEMANAME, value);
    }

    /**
     * Gets the attribute value for SCHEMA_VERSION_NUMBER using the alias name SchemaVersionNumber.
     * @return the SCHEMA_VERSION_NUMBER
     */
    public String getSchemaVersionNumber() {
        return (String) getAttributeInternal(SCHEMAVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SCHEMA_VERSION_NUMBER using the alias name SchemaVersionNumber.
     * @param value value to set the SCHEMA_VERSION_NUMBER
     */
    public void setSchemaVersionNumber(String value) {
        setAttributeInternal(SCHEMAVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for SUBMIT_DATE using the alias name SubmitDate.
     * @return the SUBMIT_DATE
     */
    public Date getSubmitDate() {
        return (Date) getAttributeInternal(SUBMITDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMIT_DATE using the alias name SubmitDate.
     * @param value value to set the SUBMIT_DATE
     */
    public void setSubmitDate(Date value) {
        setAttributeInternal(SUBMITDATE, value);
    }

    /**
     * Gets the attribute value for SUBMITTED_BY using the alias name SubmittedBy.
     * @return the SUBMITTED_BY
     */
    public String getSubmittedBy() {
        return (String) getAttributeInternal(SUBMITTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITTED_BY using the alias name SubmittedBy.
     * @param value value to set the SUBMITTED_BY
     */
    public void setSubmittedBy(String value) {
        setAttributeInternal(SUBMITTEDBY, value);
    }

    /**
     * Gets the attribute value for REQUEST_ID using the alias name RequestId1.
     * @return the REQUEST_ID
     */
    public BigDecimal getRequestId1() {
        return (BigDecimal) getAttributeInternal(REQUESTID1);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId1.
     * @param value value to set the REQUEST_ID
     */
    public void setRequestId1(BigDecimal value) {
        setAttributeInternal(REQUESTID1, value);
    }

    /**
     * Gets the attribute value for IS_REVIEWED using the alias name IsReviewed.
     * @return the IS_REVIEWED
     */
    public String getIsReviewed() {
        return (String) getAttributeInternal(ISREVIEWED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_REVIEWED using the alias name IsReviewed.
     * @param value value to set the IS_REVIEWED
     */
    public void setIsReviewed(String value) {
        setAttributeInternal(ISREVIEWED, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TransactionStatusLOV1.
     */
    public RowSet getTransactionStatusLOV1() {
        return (RowSet)getAttributeInternal(TRANSACTIONSTATUSLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
