package gov.ca.dir.acct.cars.adf.usecase004.model.appmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 27 00:09:29 PST 2013
// ---------------------------------------------------------------------
public interface InboundTransactionMngrAM extends ApplicationModule {
    void setCriteriaParams(String varStatus, String varIsReviewed);
}
