package gov.ca.dir.acct.cars.adf.usecase009.model.view.client;

import gov.ca.dir.acct.cars.adf.usecase009.model.view.common.Infar006VO;

import java.math.BigDecimal;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 19 11:59:00 PDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Infar006VOClient extends ViewUsageImpl implements Infar006VO {
  /**
   * This is the default constructor (do not remove).
   */
  public Infar006VOClient() {
  }

  public void setBatchIdBindVC(BigDecimal batchId) {
    Object _ret =
      getApplicationModuleProxy().riInvokeExportedMethod(this,"setBatchIdBindVC",new String [] {"java.math.BigDecimal"},new Object[] {batchId});
    return;
  }
}
