package gov.ca.dir.acct.cars.adf.usecase001.model.CarsEventDetails;

import java.math.BigDecimal;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 25 15:55:38 PDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AccountingEntryStatusViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AcctgEntryId {
            public Object get(AccountingEntryStatusViewRowImpl obj) {
                return obj.getAcctgEntryId();
            }

            public void put(AccountingEntryStatusViewRowImpl obj,
                            Object value) {
                obj.setAcctgEntryId((BigDecimal)value);
            }
        }
        ,
        FsProcessDate {
            public Object get(AccountingEntryStatusViewRowImpl obj) {
                return obj.getFsProcessDate();
            }

            public void put(AccountingEntryStatusViewRowImpl obj,
                            Object value) {
                obj.setFsProcessDate((Date)value);
            }
        }
        ,
        FsProcessStatus {
            public Object get(AccountingEntryStatusViewRowImpl obj) {
                return obj.getFsProcessStatus();
            }

            public void put(AccountingEntryStatusViewRowImpl obj,
                            Object value) {
                obj.setFsProcessStatus((String)value);
            }
        }
        ,
        AcctgTransactionId {
            public Object get(AccountingEntryStatusViewRowImpl obj) {
                return obj.getAcctgTransactionId();
            }

            public void put(AccountingEntryStatusViewRowImpl obj,
                            Object value) {
                obj.setAcctgTransactionId((BigDecimal)value);
            }
        }
        ,
        AcctgEntryId1 {
            public Object get(AccountingEntryStatusViewRowImpl obj) {
                return obj.getAcctgEntryId1();
            }

            public void put(AccountingEntryStatusViewRowImpl obj,
                            Object value) {
                obj.setAcctgEntryId1((BigDecimal)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(AccountingEntryStatusViewRowImpl object);

        public abstract void put(AccountingEntryStatusViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ACCTGENTRYID = AttributesEnum.AcctgEntryId.index();
    public static final int FSPROCESSDATE = AttributesEnum.FsProcessDate.index();
    public static final int FSPROCESSSTATUS = AttributesEnum.FsProcessStatus.index();
    public static final int ACCTGTRANSACTIONID = AttributesEnum.AcctgTransactionId.index();
    public static final int ACCTGENTRYID1 = AttributesEnum.AcctgEntryId1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AccountingEntryStatusViewRowImpl() {
    }

    /**
     * Gets AccountingEntryStatus entity object.
     * @return the AccountingEntryStatus
     */
    public EntityImpl getAccountingEntryStatus() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets AccountingEntry entity object.
     * @return the AccountingEntry
     */
    public EntityImpl getAccountingEntry() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets the attribute value for ACCTG_ENTRY_ID using the alias name AcctgEntryId.
     * @return the ACCTG_ENTRY_ID
     */
    public BigDecimal getAcctgEntryId() {
        return (BigDecimal) getAttributeInternal(ACCTGENTRYID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCTG_ENTRY_ID using the alias name AcctgEntryId.
     * @param value value to set the ACCTG_ENTRY_ID
     */
    public void setAcctgEntryId(BigDecimal value) {
        setAttributeInternal(ACCTGENTRYID, value);
    }

    /**
     * Gets the attribute value for FS_PROCESS_DATE using the alias name FsProcessDate.
     * @return the FS_PROCESS_DATE
     */
    public Date getFsProcessDate() {
        return (Date) getAttributeInternal(FSPROCESSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FS_PROCESS_DATE using the alias name FsProcessDate.
     * @param value value to set the FS_PROCESS_DATE
     */
    public void setFsProcessDate(Date value) {
        setAttributeInternal(FSPROCESSDATE, value);
    }

    /**
     * Gets the attribute value for FS_PROCESS_STATUS using the alias name FsProcessStatus.
     * @return the FS_PROCESS_STATUS
     */
    public String getFsProcessStatus() {
        return (String) getAttributeInternal(FSPROCESSSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for FS_PROCESS_STATUS using the alias name FsProcessStatus.
     * @param value value to set the FS_PROCESS_STATUS
     */
    public void setFsProcessStatus(String value) {
        setAttributeInternal(FSPROCESSSTATUS, value);
    }

    /**
     * Gets the attribute value for ACCTG_TRANSACTION_ID using the alias name AcctgTransactionId.
     * @return the ACCTG_TRANSACTION_ID
     */
    public BigDecimal getAcctgTransactionId() {
        return (BigDecimal) getAttributeInternal(ACCTGTRANSACTIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCTG_TRANSACTION_ID using the alias name AcctgTransactionId.
     * @param value value to set the ACCTG_TRANSACTION_ID
     */
    public void setAcctgTransactionId(BigDecimal value) {
        setAttributeInternal(ACCTGTRANSACTIONID, value);
    }

    /**
     * Gets the attribute value for ACCTG_ENTRY_ID using the alias name AcctgEntryId1.
     * @return the ACCTG_ENTRY_ID
     */
    public BigDecimal getAcctgEntryId1() {
        return (BigDecimal) getAttributeInternal(ACCTGENTRYID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCTG_ENTRY_ID using the alias name AcctgEntryId1.
     * @param value value to set the ACCTG_ENTRY_ID
     */
    public void setAcctgEntryId1(BigDecimal value) {
        setAttributeInternal(ACCTGENTRYID1, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
