package gov.ca.dir.acct.cars.adf.usecase001.model.CarsEventDetails;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 25 15:55:38 PDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AccountingEntryStatusViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AccountingEntryStatusViewImpl() {
    }
}
