package gov.ca.dir.acct.cars.adf.usecase001.model.CarsEventDetails;


import gov.ca.dir.acct.cars.adf.usecase001.model.CarsEventDetails.ViewArRootDocumentsImpl;
import gov.ca.dir.acct.cars.adf.usecase001.model.CarsEventDetails.common.CarsSearchEvents;

import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 30 11:40:39 PST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CarsSearchEventsImpl extends ApplicationModuleImpl implements CarsSearchEvents {
    /**
     * This is the default constructor (do not remove).
     */
    public CarsSearchEventsImpl() {
    }

    /**
     * Container's getter for ViewEvents1.
     * @return ViewEvents1
     */
    public ViewObjectImpl getViewEvents1() {
        return (ViewObjectImpl)findViewObject("ViewEvents1");
    }

    /**
     * Container's getter for ViewTcDetails1.
     * @return ViewTcDetails1
     */
    public ViewObjectImpl getViewTcDetails1() {
        return (ViewObjectImpl)findViewObject("ViewTcDetails1");
    }

    /**
     * Container's getter for ViewEventDetails2.
     * @return ViewEventDetails2
     */
    public ViewObjectImpl getViewEventDetails2() {
        return (ViewObjectImpl)findViewObject("ViewEventDetails2");
    }

    /**
     * Container's getter for ViewTcDetails2.
     * @return ViewTcDetails2
     */
    public ViewObjectImpl getViewTcDetails2() {
        return (ViewObjectImpl)findViewObject("ViewTcDetails2");
    }

    /**
     * Container's getter for ViewArRootDocuments1.
     * @return ViewArRootDocuments1
     */
    public ViewObjectImpl getViewArRootDocuments1() {
        return (ViewObjectImpl)findViewObject("ViewArRootDocuments1");
    }

    /**
     * Container's getter for ViewEvents2.
     * @return ViewEvents2
     */
    public ViewObjectImpl getViewEvents2() {
        return (ViewObjectImpl)findViewObject("ViewEvents2");
    }

    /**
     * Container's getter for ViewEventDetails1.
     * @return ViewEventDetails1
     */
    public ViewObjectImpl getViewEventDetails1() {
        return (ViewObjectImpl)findViewObject("ViewEventDetails1");
    }

    /**
     * Container's getter for ViewTcDetails3.
     * @return ViewTcDetails3
     */
    public ViewObjectImpl getViewTcDetails3() {
        return (ViewObjectImpl)findViewObject("ViewTcDetails3");
    }

    /**
     * Container's getter for ViewEventDetails3.
     * @return ViewEventDetails3
     */
    public ViewObjectImpl getViewEventDetails3() {
        return (ViewObjectImpl)findViewObject("ViewEventDetails3");
    }

    /**
     * Container's getter for BatchTransactionView1.
     * @return BatchTransactionView1
     */
    public ViewObjectImpl getBatchTransactionView1() {
        return (ViewObjectImpl)findViewObject("BatchTransactionView1");
    }

    /**
     * Container's getter for ViewBalanceByGlAndArRootDoc1.
     * @return ViewBalanceByGlAndArRootDoc1
     */
    public ViewObjectImpl getViewBalanceByGlAndArRootDoc1() {
        return (ViewObjectImpl)findViewObject("ViewBalanceByGlAndArRootDoc1");
    }

    /**
     * Container's getter for ViewArRootDocuments2.
     * @return ViewArRootDocuments2
     */
    public ViewObjectImpl getViewArRootDocuments2() {
        return (ViewObjectImpl)findViewObject("ViewArRootDocuments2");
    }

    /**
     * Container's getter for ViewBalanceByGlAndArRootDoc2.
     * @return ViewBalanceByGlAndArRootDoc2
     */
    public ViewObjectImpl getViewBalanceByGlAndArRootDoc2() {
        return (ViewObjectImpl)findViewObject("ViewBalanceByGlAndArRootDoc2");
    }

    /**
     * Container's getter for BatchTransactionView2.
     * @return BatchTransactionView2
     */
    public ViewObjectImpl getBatchTransactionView2() {
        return (ViewObjectImpl)findViewObject("BatchTransactionView2");
    }

    /**
     * Container's getter for viewLinkEventDetailsToTcDetails.
     * @return viewLinkEventDetailsToTcDetails
     */
    public ViewLinkImpl getviewLinkEventDetailsToTcDetails() {
        return (ViewLinkImpl)findViewLink("viewLinkEventDetailsToTcDetails");
    }

    /**
     * Container's getter for viewLinkEventDetailsToTcDetails1.
     * @return viewLinkEventDetailsToTcDetails1
     */
    public ViewLinkImpl getviewLinkEventDetailsToTcDetails1() {
        return (ViewLinkImpl)findViewLink("viewLinkEventDetailsToTcDetails1");
    }

    /**
     * Container's getter for EventDetailsBatchTransactionViewLink.
     * @return EventDetailsBatchTransactionViewLink
     */
    public ViewLinkImpl getEventDetailsBatchTransactionViewLink() {
        return (ViewLinkImpl)findViewLink("EventDetailsBatchTransactionViewLink");
    }

    /**
     * Container's getter for ViewArRootBalanceByGlViewLink.
     * @return ViewArRootBalanceByGlViewLink
     */
    public ViewLinkImpl getViewArRootBalanceByGlViewLink() {
        return (ViewLinkImpl)findViewLink("ViewArRootBalanceByGlViewLink");
    }

    /**
     * Container's getter for EventDetailsBatchTransactionViewLink1.
     * @return EventDetailsBatchTransactionViewLink1
     */
    public ViewLinkImpl getEventDetailsBatchTransactionViewLink1() {
        return (ViewLinkImpl)findViewLink("EventDetailsBatchTransactionViewLink1");
    }
    
    /**
     * Reset query for ViewArRootDocuments1 iterator
     */
    public void doResetViewArRootDocuments1(String searchCriteriaName) {
        ViewCriteria vc;
        
       // this.getViewArRootDocuments1().clearViewCriterias();//.removeViewCriteria("SearchCarsInvoicesCriteriaCALOSHAQuery");
        this.getViewArRootDocuments1().executeEmptyRowSet();
        if  (searchCriteriaName.equals("CALOSHA"))  {
            vc = this.getViewArRootDocuments1().getViewCriteria("SearchCarsInvoicesCriteriaCALOSHA");
        }
        else if  (searchCriteriaName.equals("DLSE"))  {
            vc = this.getViewArRootDocuments1().getViewCriteria("SearchCarsInvoicesCriteriaDLSE");
        }
        else if (searchCriteriaName.equals("ART")) {
            vc = this.getViewArRootDocuments1().getViewCriteria("SearchCarsInvoicesCriteriaART");
        }
        else if (searchCriteriaName.equals("PV")) {
            vc = this.getViewArRootDocuments1().getViewCriteria("SearchCarsInvoicesCriteriaPV");
        }
        else if (searchCriteriaName.equals("EV")) {
            vc = this.getViewArRootDocuments1().getViewCriteria("SearchCarsInvoicesCriteriaEV");
        }
        else {
            vc = this.getViewArRootDocuments1().getViewCriteria("SearchCarsInvoicesCriteriaANY");
        }
        this.getViewArRootDocuments1().applyViewCriteria(vc,false); 
        //this.getViewArRootDocuments1().executeQuery();
    }

    /**
     * Container's getter for NoteView1.
     * @return NoteView1
     */
    public ViewObjectImpl getNoteView1() {
        return (ViewObjectImpl)findViewObject("NoteView1");
    }

    /**
     * Container's getter for NoteEventVO1.
     * @return NoteEventVO1
     */
    public ViewObjectImpl getNoteEventVO1() {
        return (ViewObjectImpl)findViewObject("NoteEventVO1");
    }

    /**
     * Container's getter for NoteEventVO2.
     * @return NoteEventVO2
     */
    public ViewObjectImpl getNoteEventVO2() {
        return (ViewObjectImpl)findViewObject("NoteEventVO2");
    }

    /**
     * Container's getter for ViewArBalance1.
     * @return ViewArBalance1
     */
    public ViewObjectImpl getViewArBalance1() {
        return (ViewObjectImpl)findViewObject("ViewArBalance1");
    }

    /**
     * Container's getter for EventTypeView1.
     * @return EventTypeView1
     */
    public ViewObjectImpl getEventTypeView1() {
        return (ViewObjectImpl)findViewObject("EventTypeView1");
    }

    /**
     * Container's getter for ProgramUnitView1.
     * @return ProgramUnitView1
     */
    public ViewObjectImpl getProgramUnitView1() {
        return (ViewObjectImpl)findViewObject("ProgramUnitView1");
    }


    /**
     * Container's getter for ViewInitiatingEvents2.
     * @return ViewInitiatingEvents2
     */
    public ViewObjectImpl getViewInitiatingEvents1() {
        return (ViewObjectImpl)findViewObject("ViewInitiatingEvents1");
    }

    /**
     * Container's getter for ViewChildEvents1.
     * @return ViewChildEvents1
     */
    public ViewObjectImpl getViewChildEvents1() {
        return (ViewObjectImpl)findViewObject("ViewChildEvents1");
    }

    /**
     * Container's getter for ViewChildOfInitiatingViewLink.
     * @return ViewChildOfInitiatingViewLink
     */
    public ViewLinkImpl getViewChildOfInitiatingViewLink() {
        return (ViewLinkImpl)findViewLink("ViewChildOfInitiatingViewLink");
    }


    /**
     * Container's getter for ViewArRootDocuments3.
     * @return ViewArRootDocuments3
     */
    public ViewArRootDocumentsImpl getSearchCALOSHA() {
        return (ViewArRootDocumentsImpl)findViewObject("SearchCALOSHA");
    }

    /**
     * Container's getter for ViewArRootDocuments3.
     * @return ViewArRootDocuments3
     */
    public ViewArRootDocumentsImpl getSearchDLSE() {
        return (ViewArRootDocumentsImpl)findViewObject("SearchDLSE");
    }

    /**
     * Container's getter for ViewArRootDocuments3.
     * @return ViewArRootDocuments3
     */
    public ViewArRootDocumentsImpl getSearchPV() {
        return (ViewArRootDocumentsImpl)findViewObject("SearchPV");
    }

    /**
     * Container's getter for SearchART.
     * @return SearchART
     */
    public ViewArRootDocumentsImpl getSearchART() {
        return (ViewArRootDocumentsImpl)findViewObject("SearchART");
    }

    /**
     * Container's getter for SearchEV.
     * @return SearchEV
     */
    public ViewArRootDocumentsImpl getSearchEV() {
        return (ViewArRootDocumentsImpl)findViewObject("SearchEV");
    }

    /**
     * Container's getter for SearchAll.
     * @return SearchAll
     */
    public ViewArRootDocumentsImpl getSearchAll() {
        return (ViewArRootDocumentsImpl)findViewObject("SearchAll");
    }

    /**
     * Container's getter for GetArRootDocumentGlBalancesView1.
     * @return GetArRootDocumentGlBalancesView1
     */
    public ViewObjectImpl getGetArRootDocumentGlBalancesView1() {
        return (ViewObjectImpl)findViewObject("GetArRootDocumentGlBalancesView1");
    }

    /**
     * Container's getter for ReceiptView1.
     * @return ReceiptView1
     */
    public ReceiptViewImpl getReceiptView1() {
        return (ReceiptViewImpl)findViewObject("ReceiptView1");
    }


    /**
     * Container's getter for OrgParticipantRoleAddressView1.
     * @return OrgParticipantRoleAddressView1
     */
    public ViewObjectImpl getOrgParticipantRoleAddressView1() {
        return (ViewObjectImpl)findViewObject("OrgParticipantRoleAddressView1");
    }

    /**
     * Container's getter for ViewArRootDocsOrgPartiRoleAddressViewLink1.
     * @return ViewArRootDocsOrgPartiRoleAddressViewLink1
     */
    public ViewLinkImpl getViewArRootDocsOrgPartiRoleAddressViewLink1() {
        return (ViewLinkImpl)findViewLink("ViewArRootDocsOrgPartiRoleAddressViewLink1");
    }

    /**
     * Container's getter for AccountingEntryStatusView1.
     * @return AccountingEntryStatusView1
     */
    public AccountingEntryStatusViewImpl getAccountingEntryStatusView1() {
        return (AccountingEntryStatusViewImpl)findViewObject("AccountingEntryStatusView1");
    }

    /**
     * Container's getter for ReceiptAccountingEntryStatusViewLink1.
     * @return ReceiptAccountingEntryStatusViewLink1
     */
    public ViewLinkImpl getReceiptAccountingEntryStatusViewLink1() {
        return (ViewLinkImpl)findViewLink("ReceiptAccountingEntryStatusViewLink1");
    }

    /**
     * Container's getter for OrgParticipantRoleAddressView2.
     * @return OrgParticipantRoleAddressView2
     */
    public ViewObjectImpl getOrgParticipantRoleAddressView2() {
        return (ViewObjectImpl)findViewObject("OrgParticipantRoleAddressView2");
    }

    /**
     * Container's getter for ViewEventsOrgParticipantRoleAddressViewLink1.
     * @return ViewEventsOrgParticipantRoleAddressViewLink1
     */
    public ViewLinkImpl getViewEventsOrgParticipantRoleAddressViewLink1() {
        return (ViewLinkImpl)findViewLink("ViewEventsOrgParticipantRoleAddressViewLink1");
    }
}
