package gov.ca.dir.acct.cars.adf.usecase001.model.CarsEventDetails;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 09 17:06:23 PDT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewEventsImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ViewEventsImpl() {
    }

    /**
     * Returns the variable value for varRootDocument.
     * @return variable value for varRootDocument
     */
    public String getvarRootDocument() {
        return (String)ensureVariableManager().getVariableValue("varRootDocument");
    }

    /**
     * Sets <code>value</code> for variable varRootDocument.
     * @param value value to bind as varRootDocument
     */
    public void setvarRootDocument(String value) {
        ensureVariableManager().setVariableValue("varRootDocument", value);
    }
}
