package gov.ca.dir.acct.cars.adf.usecase009.model.view.common;

import java.math.BigDecimal;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 19 13:36:23 PDT 2018
// ---------------------------------------------------------------------
public interface Infar001VO extends ViewObject {
  void set001BatchIdVC(BigDecimal batchId);
}
