package gov.ca.dir.acct.cars.adf.usecase009.model.view.common;

import java.math.BigDecimal;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 19 11:59:00 PDT 2018
// ---------------------------------------------------------------------
public interface Infar006VO extends ViewObject {
  void setBatchIdBindVC(BigDecimal batchId);
}
