package gov.ca.dir.acct.cars.adf.service.appmodule.client;

import gov.ca.dir.acct.cars.adf.service.appmodule.common.CarsBCUtilityServicesAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 03 13:25:20 PDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CarsBCUtilityServicesAMClient extends ApplicationModuleImpl implements CarsBCUtilityServicesAM {
    /**
     * This is the default constructor (do not remove).
     */
    public CarsBCUtilityServicesAMClient() {
    }


    public Number getAcctgEntrySequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getAcctgEntrySequence",null,null);
        return (Number)_ret;
    }


    public String getFiscalYear(String currentDocumentNumber) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getFiscalYear",new String [] {"java.lang.String"},new Object[] {currentDocumentNumber});
        return (String)_ret;
    }


    public Number isDecisionAfterReclassExisted(String ReferenceDocument) {
        Object _ret =
            this.riInvokeExportedMethod(this,"isDecisionAfterReclassExisted",new String [] {"java.lang.String"},new Object[] {ReferenceDocument});
        return (Number)_ret;
    }


    public Number getEventIDSequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getEventIDSequence",null,null);
        return (Number)_ret;
    }

    public Number getARStatusIDSequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getARStatusIDSequence",null,null);
        return (Number)_ret;
    }

    public Number getPartyIDSequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getPartyIDSequence",null,null);
        return (Number)_ret;
    }

    public Number getParticipantRoleIdSequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getParticipantRoleIdSequence",null,null);
        return (Number)_ret;
    }

    public Number getContactMethodIdSequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getContactMethodIdSequence",null,null);
        return (Number)_ret;
    }

    public Number getAddressIdSequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getAddressIdSequence",null,null);
        return (Number)_ret;
    }

    public Number getAcctgTransactionIdSequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getAcctgTransactionIdSequence",null,null);
        return (Number)_ret;
    }

    public Number getAcctgEntryIdSequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getAcctgEntryIdSequence",null,null);
        return (Number)_ret;
    }

    public Number getNoteIdSequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getNoteIdSequence",null,null);
        return (Number)_ret;
    }

    public Number isEventReversed(String currentDocumentNumber) {
        Object _ret =
            this.riInvokeExportedMethod(this,"isEventReversed",new String [] {"java.lang.String"},new Object[] {currentDocumentNumber});
        return (Number)_ret;
    }

    public Number getCurrentBalance(String ReferenceDocument) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCurrentBalance",new String [] {"java.lang.String"},new Object[] {ReferenceDocument});
        return (Number)_ret;
    }

    public Number isAROthersRefDocExisted(String ReferenceDocument) {
        Object _ret =
            this.riInvokeExportedMethod(this,"isAROthersRefDocExisted",new String [] {"java.lang.String"},new Object[] {ReferenceDocument});
        return (Number)_ret;
    }

    public Number isReclassNeeded(String ReferenceDocument) {
        Object _ret =
            this.riInvokeExportedMethod(this,"isReclassNeeded",new String [] {"java.lang.String"},new Object[] {ReferenceDocument});
        return (Number)_ret;
    }

    public Number isDecisionAfterReclassExisted(String ReferenceDocument,
                                                String eventDateStr,
                                                String eventTypeCode) {
        Object _ret =
            this.riInvokeExportedMethod(this,"isDecisionAfterReclassExisted",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {ReferenceDocument, eventDateStr, eventTypeCode});
        return (Number)_ret;
    }

    public Number is2YearsPrior(String ReferenceDocument) {
        Object _ret =
            this.riInvokeExportedMethod(this,"is2YearsPrior",new String [] {"java.lang.String"},new Object[] {ReferenceDocument});
        return (Number)_ret;
    }

    public Number isChildrenExist(String currentDocumentNumber) {
        Object _ret =
            this.riInvokeExportedMethod(this,"isChildrenExist",new String [] {"java.lang.String"},new Object[] {currentDocumentNumber});
        return (Number)_ret;
    }
}
