package gov.ca.dir.acct.cars.adf.service.appmodule.client;

import gov.ca.dir.acct.cars.adf.service.appmodule.common.CarsBCLoggingServicesAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 01 14:26:04 PDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CarsBCLoggingServicesAMClient extends ApplicationModuleImpl implements CarsBCLoggingServicesAM {
    /**
     * This is the default constructor (do not remove).
     */
    public CarsBCLoggingServicesAMClient() {
    }

    public Number getRequestIdSequence() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getRequestIdSequence",null,null);
        return (Number)_ret;
    }

    public Number getRequestIdWithParam(String compositeInstanceId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getRequestIdWithParam",new String [] {"java.lang.String"},new Object[] {compositeInstanceId});
        return (Number)_ret;
    }
}
