package gov.ca.dir.acct.cars.adf.service.appmodule.client;

import gov.ca.dir.acct.cars.adf.service.appmodule.common.CarsBCLookupServicesAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 11 07:58:30 PDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CarsBCLookupServicesAMClient extends ApplicationModuleImpl implements CarsBCLookupServicesAM {
    /**
     * This is the default constructor (do not remove).
     */
    public CarsBCLookupServicesAMClient() {
    }


    public String getSOARecipient() {
        Object _ret =
            this.riInvokeExportedMethod(this,"getSOARecipient",null,null);
        return (String)_ret;
    }


    public String findFiscalPeriodIdWithParams(String rootDocument) {
        Object _ret =
            this.riInvokeExportedMethod(this,"findFiscalPeriodIdWithParams",new String [] {"java.lang.String"},new Object[] {rootDocument});
        return (String)_ret;
    }

    public Number recheckReferenceDocument(String referenceDocument,
                                           int processNum, long waitTime) {
        Object _ret =
            this.riInvokeExportedMethod(this,"recheckReferenceDocument",new String [] {"java.lang.String","int","long"},new Object[] {referenceDocument, new Integer(processNum), new Long(waitTime)});
        return (Number)_ret;
    }

    public String findSOARecipient() {
        Object _ret =
            this.riInvokeExportedMethod(this,"findSOARecipient",null,null);
        return (String)_ret;
    }

    public String validateAddress(String state, String zipCode,
                                  String province, String postalCode,
                                  String countryAbbreviation) {
        Object _ret =
            this.riInvokeExportedMethod(this,"validateAddress",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {state, zipCode, province, postalCode, countryAbbreviation});
        return (String)_ret;
    }
}
